Improve DarkMode (TitleBar and ScrollBar)
notepad-plus-plus/notepad-plus-plus pull request #10023
Opened 2021-06-17 14:23 UTC by ozone10

Make DarkMode title bar to apply on all dialog windows. (Now should be missing only message box dialog windows)
Make DarkMode scrollbar more reliable. (now it should be possible to remove IatHook.h)
Add softer theme to tree- and list-view.

Remove border from clipboard history panel.
This maybe needs some improvements.

fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10022
partially fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9958

2021-06-18 14:14 UTC, donho commented
@ozone10 
Thank you for your PR.
However, I don't see the difference before & after applying your PR.
A screenshot of comparison will help.

2021-06-18 15:46 UTC, ozone10 commented
Note the dialog windows title bar and scrollbar in ascii panel
Notepad++ v8.1
![image](https://user-images.githubusercontent.com/55940305/122585845-78a2ec80-d04b-11eb-9c4e-991487c13012.png)


This pull request
![image](https://user-images.githubusercontent.com/55940305/122585608-35e11480-d04b-11eb-8558-ab8231d8c7e9.png)

Now dark title bar is applied almost everywhere, I think it is missing only for windows created by MessageBox function

2021-06-19 22:49 UTC, donho reviewed
Make 2 PR 1 for Titlebar, another for ScrollBar.

2021-06-19 22:49 UTC, donho requested changes
Make 2 PR 1 for Titlebar, another for ScrollBar.

2021-06-20 06:19 UTC, ozone10 commented
They are using same function. Should I split the function `void setDarkThemeViaWinAPI(HWND hwnd, bool setTitle);`
to one with "bool true" and one with "bool false".

2021-06-20 08:33 UTC, ozone10 commented
Now only affect title bar.

2021-06-20 11:29 UTC, donho commented
@ozone10 
Thank you, the code is more readable now.
However, there is a regression comes with this PR: while we are in full dark mode (ie. restart Notepad++ to have titlebar and scrollbar in black), then we switch in light mode, the titlebar doesn't turn light.
The current implementation turns the titlebar light without restarting Notepad++.

2021-06-20 11:30 UTC, donho approved these changes

2021-06-20 11:32 UTC, donho requested changes
Fix the regression that titlebar doesn't turn into light mode directly.

2021-06-20 15:26 UTC, donho commented
@ozone10 
Almost...
![image](https://user-images.githubusercontent.com/90293/122679829-ad9a7500-d1ec-11eb-9e1f-9fb7fd8f6bfa.png)

2021-06-20 16:46 UTC, donho commented on PowerEditor/src/WinControls/ClipboardHistory/clipboardHistoryPanel.rc
> +	LISTBOX         IDC_LIST_CLIPBOARD,50,44,78,120,LBS_OWNERDRAWFIXED | LBS_NOINTEGRALHEIGHT | WS_VSCROLL | WS_TABSTOP | NOT WS_BORDER
Why do we need to remove `WS_BORDER` ?

2021-06-20 16:49 UTC, donho commented on PowerEditor/src/WinControls/ClipboardHistory/clipboardHistoryPanel.rc
> +	LISTBOX         IDC_LIST_CLIPBOARD,50,44,78,120,LBS_OWNERDRAWFIXED | LBS_NOINTEGRALHEIGHT | WS_VSCROLL | WS_TABSTOP | NOT WS_BORDER
OK, I see the visual effect.

2021-06-20 17:14 UTC, donho commented
@ozone10 
Now you can add Scrollbar PR please

2021-06-20 17:15 UTC, closed without merging