Dark find and replace dialog enhancement and fixes
notepad-plus-plus/notepad-plus-plus pull request #10220
Opened 2021-07-21 17:06 UTC by ozone10

Make color more consistent.
Fix bug with trackbar (Transparency option) not changing background,
when changing background color.
Fix visual glitch.
Enhancement to combobox, including DPI fixes.
Make listbox of combobox use dark scrollbar.

fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10027

2021-07-21 17:08 UTC, ozone10 commented on PowerEditor/src/NppDarkMode.cpp
> +		//DrawThemeParentBackground(hwnd, hdc, &rcClient);
This is causing visual glitch, currently only commented, in case there is some side effect.
But I have not noticed anything for now.

2021-07-21 17:10 UTC, ozone10 commented on PowerEditor/src/NppDarkMode.cpp
> +		HEXRGB(0x646464)	// edgeColor
use same color as system border

2021-07-21 17:10 UTC, ozone10 commented on PowerEditor/src/NppDarkMode.cpp
> +		HEXRGB(0x646464)	// edgeColor
use same color as system border

2021-07-21 18:41 UTC, donho requested changes
Remove all the reformatting for using "git blame" afterward.

2021-07-21 18:44 UTC, ozone10 commented
@donho 
> Remove all the reformatting for using "git blame" afterward.

you mean trimmed lines?

2021-07-21 18:50 UTC, donho commented
@ozone10 
Yes. Not only for the `git blame`, but also it's hard to review the code - I know I can hide the space from GitHub interface, but there are the other contributors with whom I apply "No formatting" rule.

2021-07-21 18:51 UTC, ozone10 commented
Ok will fix it now.

2021-07-21 19:38 UTC, ozone10 commented
btw I don't know if github support blame with ignoring whitespace.
but `git blame -w` command should allow to ignore whitespace changes

2021-07-22 01:06 UTC, donho commented
Noted. 
I use usually git blame in VS or on Github. So let's keep the current white spaces.

2021-07-22 01:50 UTC, donho approved these changes

2021-07-22 02:04 UTC, closed without merging