Retains tree state of function tree during Sort/Unsort and Save/Reload actions
notepad-plus-plus/notepad-plus-plus pull request #10322
Opened 2021-08-03 18:31 UTC by Ashfaaq18

### fix #10280 and fix #10294

below 2 gifs for fix #10280 

STR1 fix:
![funcListTreeSortProb-Str1](https://user-images.githubusercontent.com/27722888/128066782-122cc5c4-ea66-4006-87c0-cd3d957a90f1.gif)

STR2 fix:
![funcListTreeSortProb-Str2](https://user-images.githubusercontent.com/27722888/128066817-8e20eb8a-b053-4802-adc1-a7b6459f78b1.gif)

below gif for fix #10294

![funcListTreeSortProb-Str3](https://user-images.githubusercontent.com/27722888/128066976-7c4431ca-0ef9-477b-9ed2-7e7620a2dc5c.gif)

2021-08-03 21:48 UTC, Yaron10 commented
Hello @Ashfaaq18,

Brilliant! 👍 
Thank you for your work.

Some comments.

***
Have the tree in the following state.

![תמונה](https://user-images.githubusercontent.com/10229320/128088529-ead5b319-8de6-437d-8267-bf96a616bd1d.png)

Press "Sort".

**Result:**

![תמונה](https://user-images.githubusercontent.com/10229320/128088698-62764615-8700-46b3-9d69-6dd41d749f3a.png)

(The horizontal scroll bar moved to the right.
***

Expand the tree.
Select a node and scroll so that it's not visible.

On "Reload", the scroll bar position is retained and the selected node is still not visible.
On "Sort/Unsort", the selected node becomes visible and the scroll bar position is overridden.

IMO - in both cases the selected node should become visible.
(This is the behavior in File Explorer: select an item, scroll so that it's not visible and Refresh - the item becomes visible).
If trying to center the selected node would not require a lot of work/code - it might be more convenient.

***
This is not directly related to this PR.

Have the caret in the editor in function A.
**Single-click** function B in the FL.
Minimize NPP and restore.

**Result:**
The editor gets the focus and function A is selected in the FL.

2021-08-04 09:06 UTC, Ashfaaq18 commented
Hi @Yaron10 , thanks for the feedback. Ill get back to your comments once @donho takes a look at this PR

2021-08-04 11:31 UTC, ozone10 commented
@Ashfaaq18 
Your branch is several commit behind, could you rebase it on newer master.
There were changes in some files you are modifying, this could result in conflict.

2021-08-04 21:57 UTC, Yaron10 commented
@Ashfaaq18,

Great.
Thanks again.

2021-08-05 13:31 UTC, donho requested changes
Remove unnecessary diff.

2021-08-05 13:31 UTC, donho commented on PowerEditor/src/WinControls/TreeView/TreeView.cpp
> +
Please remove this diff.

2021-08-05 17:28 UTC, donho approved these changes

2021-08-05 17:36 UTC, donho commented
@Ashfaaq18 
This PR is approved and it'll be merged into master in about 1 week.
The master branch is frozen currently, the RC is being tested by the community:
https://community.notepad-plus-plus.org/topic/21599/notepad-v8-1-3-release-candidate

2021-08-08 01:15 UTC, closed without merging