Add support TypeScript
notepad-plus-plus/notepad-plus-plus pull request #10361
Opened 2021-08-09 12:59 UTC by 0xlay

Support TypeScript was added: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10353#issue-963344194

2021-08-11 11:49 UTC, donho commented
the extension "ts" is recognized as JavaScript, which applies to Cpp lexer also. What makes your PR better?
A screenshot of Before and After could help.

2021-08-11 12:19 UTC, 0xlay commented
@doho TypeScript has extensions ts, tsx. JavaScript has extensions js, jsx. These are two different languages. TypeScript has static typing, but JavaScript does not.
![](https://imgur.com/Zq040F3.png)
My PR adds TypeScript lang as a new language.

![](https://imgur.com/3q06JVk.png)

2021-08-11 21:23 UTC, donho commented
> My PR adds TypeScript lang as a new language.

Yes, I do understand what you have added in your PR. However, besides adding  TypeScript lang, I don't see the advantage of syntax highlighting in TypeScript.

2021-08-12 05:14 UTC, 0xlay commented
@donho I added new keywords to the "langs.model.xml" file for the TypeScript lang that are not in JavaScript. And some of the keywords I removed. I think the logical solution would be to add TypeScript as a new language, rather than mixing everything with one JavaScript. But it's decide you.

2021-08-12 10:52 UTC, donho requested changes
Please correct the 2 requested points.

2021-08-12 10:52 UTC, donho commented on PowerEditor/src/Notepad_plus.cpp
> +			return L_TYPESCRIPT;
Indentation should be aligned with other lines.

2021-08-12 10:52 UTC, donho commented on PowerEditor/visual.net/notepadPlus.vcxproj
> +    <Image Include="..\src\icons\clipboardPanel2.ico" />
All the diff in `notepadPlus.vcxproj` should be restored.
There's no reason to modify project file.

2021-08-12 16:25 UTC, 0xlay commented
@donho This project has a code style problem (mixing tabs and spaces). GitHub doesn't like the mixing of tabs and spaces.
![](https://imgur.com/pihHjcK.png)

2021-08-13 12:23 UTC, donho approved these changes

2021-08-13 12:32 UTC, donho commented
@0xlay 
I just realized that in dark mode there's no syntax highlighting in TypeScript document, do you mind to add it in `DarkModeDefault.xml` please ?

2021-08-13 12:37 UTC, donho commented
@0xlay 
Another request for auto-completion & function list of type script - but it could be done later.

2021-08-13 12:42 UTC, 0xlay commented
@donho Ok. I will add in next PR support dark theme and auto-completion & function list of type script

2021-08-13 18:16 UTC, closed without merging