Update german.xml to v8.1.4
notepad-plus-plus/notepad-plus-plus pull request #10428
Opened 2021-08-22 06:33 UTC by schnurlos

Following https://github.com/notepad-plus-plus/notepad-plus-plus/commit/45831ac0509e41e28a501d151809207df47d08d3#diff-a6ac7ceba70d88bf1547fd1defd760bd55052dcdb78c44f9d46d99ef1f450472 & https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2576bf884b37a916cf5f597d87e436fb59864cec#diff-a6ac7ceba70d88bf1547fd1defd760bd55052dcdb78c44f9d46d99ef1f450472

2021-08-29 14:16 UTC, MarkusBodensee commented on PowerEditor/installer/nativeLang/german.xml
>  			<SaveAllConfirm title="'Alles Speichern' Bestätigung" message="Sollen wirklich alle Dokumente gespeichert werden?
@schnurlos
`<SaveAllConfirm title="..." />` was removed completely in english.xml

It is replaced with the `<DoSaveAll title="...">` which you have already added and translated above.

See: deab93f9b50f580bc276225755c2782b20cd255a

2021-08-31 08:16 UTC, dinkumoil requested changes
Weitere Korrekturen für unzutreffende oder zumindest unverständliche Übersetzungen finden sich in #10466

2021-08-31 08:16 UTC, dinkumoil commented on PowerEditor/installer/nativeLang/german.xml
> +					<Item id="43061" name="Gestylten und markierten Text kopieren"/>
Aus Konsistenzgründen sollten die Übersetzungen mit den IDs 43055 bis 43059 "Hervorgehobenen Text kopieren - Stil X" lauten, ID 43060 sollte "Hervorgehobenen Text kopieren - Alle Stile" lauten und ID 43061 sollte "Hervorgehobenen Text aus Suche kopieren" lauten.

2021-08-31 08:16 UTC, dinkumoil commented on PowerEditor/installer/nativeLang/german.xml
> +					<Item id="6351" name="Alle Vorkommen der Markierung stilisieren"/>
Die Übersetzung mit der ID 6351 ist der Titel einer Gruppierungsbox in der Rubrik "Hervorhebung" des Einstellungsdialogs. Warum also hier die Terminologie wechseln? Besser (da konsistent) wäre es doch, hier bei "Alle Hervorheben" zu bleiben.

2021-08-31 08:16 UTC, dinkumoil commented on PowerEditor/installer/nativeLang/german.xml
>  					<Item id="6352" name="Übereinstimmung der Groß-/Kleinschreibung"/>
ID 6352 sollte mit "Groß-/Kleinschreibung beachten" übersetzt werden, analog zu ID 6332.

2021-08-31 08:16 UTC, dinkumoil commented on PowerEditor/installer/nativeLang/german.xml
>  					<Item id="6353" name="Übereinstimmung ganzes Wort"/>
Die Übersetzung für ID 6353 ist grammatikalisch falsch. Sie sollte "Übereinstimmung mit ganzem Wort" lauten, analog zu ID 6338.

2021-09-14 21:55 UTC, donho commented
@schnurlos 
Thank you for the update.
Could you please check the latest difference between v8.1.4 & v8.1.5 on the following issue:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10548

And confirm me if your translation is all updated?
Thank you.

2021-09-15 18:56 UTC, schnurlos commented
@donho Confirmed, I've just updated the last modification.

2021-09-15 19:13 UTC, MarkusBodensee commented
@schnurlos
I found at least one missing item. Can you recheck and compare with english?

The item I found from english.xml
--> `<Item id="42086" name="Date Time (customized)"/>`

2021-09-15 19:28 UTC, MarkusBodensee commented
```
                <MultiInstance title="Multi-Instance &amp; Date">
                    <Item id="6151" name="Multi-instance settings"/>
                    <Item id="6152" name="Open session in a new instance of Notepad++"/>
                    <Item id="6153" name="Always in multi-instance mode"/>
                    <Item id="6154" name="Default (mono-instance)"/>
                    <Item id="6155" name="* The modification of this setting needs to restart Notepad++"/>
                    <Item id="6171" name="Customize insert Date Time"/>
                    <Item id="6175" name="Reverse default date time order (short &amp;&amp; long formats)"/>
                    <Item id="6172" name="Custom format:"/>
                </MultiInstance>
```

2021-09-15 19:52 UTC, MarkusBodensee commented
Currently in Line 189, the below item is not present anymore in english. Furthermore, the id is now used for another item and is currently present two times.

--> Delete `<Item id="42079" name="Markierten Text in die Zwischenablage"/>`


Ok, that is all I found. Thank you for your updates :-)

2021-09-16 13:18 UTC, closed without merging