Win32file api
notepad-plus-plus/notepad-plus-plus pull request #10598
Opened 2021-09-25 18:22 UTC by pnedev

Use native Win32 API to access files (currently only used for saving files to fix the reported file corruption problems).
Settings files are still written using TinyXML library and are thus still prone to those problems.

2021-09-25 19:24 UTC, ivan-u7n commented on PowerEditor/src/MISC/Common/FileInterface.h
> +	bool Write(const void *wbuf, unsigned long buf_size);
Why not the standard `size_t` for the sizes? I'm really curious — maybe I don't know something…

2021-09-25 19:30 UTC, ivan-u7n commented on PowerEditor/src/ScintillaComponent/Buffer.cpp
> +				long items_written = 0;
…as then it seems this switching from `size_t` to `long` and later casts won't be necessary.

2021-09-26 01:14 UTC, donho requested changes
Please change the code according the following remarks:
 
1. Coding convention: Change the 1st letter of methods of CFile class to lowercase.
2. Make `Utf8_16_Write::fwrite()` return `bool`.
3. Change `long items_written = 0;` to `boolean isWrittenSuccessful = false;`.

2021-09-26 09:58 UTC, ivan-u7n commented on PowerEditor/src/MISC/Common/FileInterface.h
> +	bool Write(const void *wbuf, unsigned long buf_size);
@donho What I meant is that it seems more reasonable for these member functions to have `buf_size` or return type as `size_t` to concentrate the necessary casts or other adjustments in one spot than to spread them all over the code.

Also on a 64 bit system this code will fail to write a buffer over 4GB in size, although it's unlikely to happen, but still…

2021-09-26 12:52 UTC, pnedev commented
@donho,

Sorry, I don't have time to work or comment on that anymore.
Feel free to modify, accept, decline this PR as you find appropriate.

2021-09-26 13:49 UTC, donho commented
> Sorry, I don't have time to work or comment on that anymore.
> Feel free to modify, accept, decline this PR as you find appropriate.

OK, no problem. 
Thank you for your PR and all your effort concerning this issue.

2021-09-26 13:50 UTC, donho approved these changes

2021-09-28 10:42 UTC, closed without merging