cobol syntax updated
notepad-plus-plus/notepad-plus-plus pull request #10731
Opened 2021-10-29 16:03 UTC by GitMensch

first COBOL202x additions, added pco as common extension

One question: When checking the "default" file extension in the style settings then they don't much the ones in this file - are there taken from an external component or should I delete an old user configuration to get the new ones?

2021-10-29 21:17 UTC, donho commented on PowerEditor/src/langs.model.xml
> +            <Keywords name="instre1">configuration data declaratives division environment file file-control function function-id i-o i-o-control identification input input-output linkage local-storag
@GitMensch 
So is it the typo you made?
If so, could you do another commit to fix it?

2021-10-30 10:02 UTC, donho requested changes
Add the space after the communication.

2021-10-30 15:34 UTC, GitMensch commented
Will do so and have a look at the word list, then force-push then drop a note (but likely not today).

2021-11-05 15:48 UTC, donho commented
Absence of commit to correct the error.
Please do another PR (at your wish, of course).

2021-11-05 15:48 UTC, closed without merging