Update german.xml to V.8.1.9.2
notepad-plus-plus/notepad-plus-plus pull request #10845
Opened 2021-11-27 09:18 UTC by schnurlos

Following https://github.com/notepad-plus-plus/notepad-plus-plus/commit/add9f641043aca953545179f2e2d10690adcf64d#diff-a6ac7ceba70d88bf1547fd1defd760bd55052dcdb78c44f9d46d99ef1f450472 & https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7aa0a563200cba25f7bee3233cf78ded87341d1b#diff-a6ac7ceba70d88bf1547fd1defd760bd55052dcdb78c44f9d46d99ef1f450472

2021-12-05 00:03 UTC, donho commented
@schnurlos 
Could you take care of the PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10817 (approve or reject) the modification?

2021-12-05 00:05 UTC, donho requested changes
Approve or reject https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10817 - if approved, please put the modification into this PR.

2021-12-05 16:58 UTC, schnurlos commented
@donho approved and included in that PR.

2021-12-08 18:39 UTC, donho approved these changes

2021-12-29 23:52 UTC, closed without merging