update taiwaneseMandarin.xml to v8.1.9.2
notepad-plus-plus/notepad-plus-plus pull request #10865
Opened 2021-12-01 06:12 UTC by killgavin

update taiwaneseMandarin.xml to v8.1.9.2

2021-12-04 00:25 UTC, donho requested changes
Please follow the review comments for all the requests.

2021-12-04 00:25 UTC, donho commented on PowerEditor/installer/nativeLang/taiwaneseMandarin.xml
> +                    <Item id="46250" name="定義您的語法樣式..."/>
「您」這個字在 Notepad++ 的字典中並不存在，請您把「您」還原成「你」。

2021-12-04 00:25 UTC, donho commented on PowerEditor/installer/nativeLang/taiwaneseMandarin.xml
> +                    <Item id="6175" name="反轉默認日期時間順序（簡短與完整格式）"/>
「內定」is already used in all Taiwanese Mandarin translation, so please use 「內定」instead.

2021-12-04 00:25 UTC, donho commented on PowerEditor/installer/nativeLang/taiwaneseMandarin.xml
> +                <Item id="7" name="否(&amp;N)"/>
I kind of like 好吧 &不要啦, so please keep them.

2021-12-04 00:25 UTC, donho commented on PowerEditor/installer/nativeLang/taiwaneseMandarin.xml
> +            <common-cancel value="取消"/>
Please keep them.

2021-12-04 00:42 UTC, donho commented on PowerEditor/installer/nativeLang/taiwaneseMandarin.xml
> +                    <Item id="6175" name="反轉默認日期時間順序（簡短與完整格式）"/>
BTW 「預設」 is OK; but not 「默認」

2021-12-04 06:43 UTC, mingtsay requested changes

2021-12-04 06:43 UTC, mingtsay commented on PowerEditor/installer/nativeLang/taiwaneseMandarin.xml
> +                <Item id="1690" name="所有醒目提示"/>
醒目提示所有符合之項目，原本的順序比較符合功能目的，是否考慮還原此字串修改？

2021-12-08 18:35 UTC, donho commented
Close due to the absence of reply.

2021-12-08 18:35 UTC, closed without merging