Add copy name/path commands to Doc. List and Edit menu
notepad-plus-plus/notepad-plus-plus pull request #10993
Opened 2022-01-04 16:08 UTC by mere-human

Add new commands to copy selected files name/path into multi-selection
context menu in Document List.
Add new commands to copy all files name/path into Edit > Copy to Clipboard.
Create a new function buf2Clipborad() to be used in all similar commands.
Add new translation strings.
Also, fix the translation of the Document List multi-selection context menu.

Fix #10394

2022-01-04 16:08 UTC, mere-human commented
I had some free time and felt like contributing. So I decided to fix some items assigned to me.

2022-01-04 16:13 UTC, mere-human commented
How to test:

1. Create several new documents
2. Open some existing files, some read-only
3. View > Document List
4. Select several or all files
5. RMB > Copy selected path/name
![Screenshot 2022-01-04 180003](https://user-images.githubusercontent.com/9664141/148088979-4e87d2a1-4ea1-4942-a554-8758b990278e.png)
6. Paste to a file
7. Expected result: file names separated by a new line
8. Edit > Copy to Clipboard > All name/path
![Screenshot 2022-01-04 180108](https://user-images.githubusercontent.com/9664141/148088992-33dddab2-81c2-4f09-b9cc-808f24028f16.png)

9. Do steps 6-7
11. Now clone/move some of the file to another view
12. Do steps 5-9 and verify the result

2022-01-04 16:53 UTC, Yaron10 commented
@mere-human,

I'm glad you're back. :)
👍 

The _Copy Names/Paths_ commands in _Edit -> Copy To Clipboard_ work perfectly.

In the _Document List_ I get a blank context-menu.
(I haven't updated the localization file).
![תמונה](https://user-images.githubusercontent.com/10229320/148094002-a8ac4b39-0568-49cd-b607-50ce4e454017.png)

Thank you for your work.

2022-01-04 21:08 UTC, mere-human commented
> In the _Document List_ I get a blank context-menu.
> (I haven't updated the localization file).

Fixed.

2022-01-04 21:41 UTC, Yaron10 commented
Great. It works like a charm. 👍 

Thanks again.

2022-01-05 01:05 UTC, donho requested changes
1. Please change the commented points.
2. Make 2 menu commands shortcutable.
3. Make 2 menu commands recordable.

2022-01-05 14:16 UTC, mere-human commented
> * Make 2 menu commands shortcutable.
> * Make 2 menu commands recordable.

Done. I did this for Edit > Copy to Clipboard > All name/path commands. 
I didn't do this for context menu entries in Document List, because:
- it won't work without a selection in Document List
- there are no shortcuts/macro for other entries in that context menu

2022-01-05 14:32 UTC, donho approved these changes

2022-01-05 15:07 UTC, closed without merging