fixed exception handling in FileManager::loadFileData
notepad-plus-plus/notepad-plus-plus pull request #11112
Opened 2022-02-01 01:31 UTC by xomx

- fix for unnecessary GCC crashes when opening larger files in 32-bit N++
- enhance the exception handling & reporting there

Fixes: #11103

2022-02-01 20:55 UTC, xomx commented
Functionality for GCC builds seems to be ok.
Also handling of all the Scintilla error statuses + possible SEH-exceptions works.

But maybe I should rephrase 'opening' to 'loading' in the "FileOpeningException" and "An error occurred while opening the file!"?

2022-02-04 16:35 UTC, donho requested changes
Please consider all the comments in the code review.

2022-02-04 17:38 UTC, xomx commented on PowerEditor/src/ScintillaComponent/Buffer.cpp
> +				_stprintf_s(szException, _countof(szException), TEXT("0x%X (SEH)"), ::GetExceptionCode());
I will recheck this, when I will be at my usual PC, but I think that the `GetExceptionCode()` is officially unsupported for GNUC.

I did a quick look into MINGW source code and there are some possibilities indeed (e.g. __try1/__except1 macros in excpt.h). But I have to study that first, I usually do not use MINGW. 

There is also a [callback posibility](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-crt/crt/crt_handler.c#l188). But this seems to be incompatible with MINGW x86.

2022-02-04 23:11 UTC, donho commented on PowerEditor/src/ScintillaComponent/Buffer.cpp
> +				_stprintf_s(szException, _countof(szException), TEXT("0x%X (SEH)"), ::GetExceptionCode());
OK. I see.  Please let me know if there's any option to remove `#if`

2022-02-05 19:17 UTC, xomx commented on PowerEditor/src/ScintillaComponent/Buffer.cpp
> +				_stprintf_s(szException, _countof(szException), TEXT("0x%X (SEH)"), ::GetExceptionCode());
Could you please accept this PR in its current state?

I will continue to look into this, but I need more time for installing and testing under the MINGW and I do not want to hold off a possible progress elsewhere. If I find something solid for replacing this `#if`, then I will do another PR. Is that ok?

2022-02-07 22:22 UTC, donho commented on PowerEditor/src/ScintillaComponent/Buffer.cpp
> +				_stprintf_s(szException, _countof(szException), TEXT("0x%X (SEH)"), ::GetExceptionCode());
@xomx 
OK. Thank you for the help and coding effort.

2022-02-07 22:35 UTC, closed without merging