Update Slovak translation to 8.3.2
notepad-plus-plus/notepad-plus-plus pull request #11264
Opened 2022-02-22 09:03 UTC by kubalav

2022-02-22 22:49 UTC, donho requested changes
Could you consider the changes in:
ee765135be97808d68d04700a349abb9ac0ad41d & 3de15f55129fb54fd804f9b5bb4f59ff4fd8c4fb

2022-02-23 09:14 UTC, kubalav commented
I pushed changes from old branch, but all changes are incorporated now.

2022-02-23 13:48 UTC, donho approved these changes

2022-02-23 13:53 UTC, donho commented
@kubalav 
I've got some error during the merge:
```
$ git rebase -i
error: could not apply 4124bc7b... Update Slovak translation to 8.3.0
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```

Please create a new branch from the master of the current state and add your modification in the new branch to create a new PR. 
Thank you

2022-02-23 13:53 UTC, closed without merging