fix for the possible crash when loading an older session file
notepad-plus-plus/notepad-plus-plus pull request #11327
Opened 2022-03-02 21:39 UTC by xomx

The 2GB+ adaptation has forced the change in session integers saving via TinyXML (now saving indirectly as strings). While the `MapPosition` part inside the `NppParameters::getSessionFromXmlTree()` has been already fortified against possible missing session-file internal items, the `Position` part not. So implemented likewise the `MapPosition` way there.

Fixes #11325 .

2022-03-02 22:32 UTC, Yaron10 commented
@xomx,

👍 
Thank you for the quick fix.

2022-03-03 01:58 UTC, donho commented
No, it's not enough.
You have review ca8c302805f882ed61717bb26efbc141a6991ea7 to fix the crash.

2022-03-03 01:59 UTC, donho requested changes
Review ca8c302805f882ed61717bb26efbc141a6991ea7 to add the fix for preventing the crash.

2022-03-03 19:00 UTC, xomx commented
@donho 

I re-checked and I did not find any other problem like that in the rest of my 2GB+ patch.

The relevant problematic part of the `NppParameters::getSessionFromXmlTree()` worked ok before my 2GB+ patch, because of the underlying TinyXML `TiXmlElement::Attribute( const TCHAR * name, int* i )` returns 0 as a default in the `i` in case of invalid/missing `name` of the item from the session.xml file.


The rest of the code, I rewrote in my 2GB+ patch, has already been of the following type anyway, so it took into account even a possible NULL-string:
```
int32_t mapPosVal;
const TCHAR* mapPosStr = (childNode->ToElement())->Attribute(TEXT("mapFirstVisibleDisplayLine"), &mapPosVal);
if (mapPosStr)
	mapPosition._firstVisibleDisplayLine = mapPosVal;
```

2022-03-04 12:33 UTC, donho approved these changes

2022-03-04 12:45 UTC, closed without merging