Label positioning in FindReplaceDlg + layout improvement
notepad-plus-plus/notepad-plus-plus pull request #11320
Opened 2022-03-02 09:19 UTC by dfs-

* move labels to resemble v8.2 positioning
* resize IDD_FINDINFILES_DIR_COMBO to make it end with the other comboboxes
* resize IDD_FINDINFILES_BROWSE_BUTTON to match combobox height
* make IDD_FINDREPLACE_SWAP_BUTTON in line with IDD_FINDINFILES_BROWSE_BUTTON

Fixes #11318 and improves the layout

**New Layout:**
![pr](https://user-images.githubusercontent.com/6563013/156332273-c1dbf618-c3f0-4660-9e6d-8281417416ff.png)

2022-03-02 21:16 UTC, donho commented
The result of this PR to me is not nice:

![image](https://user-images.githubusercontent.com/90293/156450882-da7e8eca-df2b-489f-b181-de7591dc6bd2.png)

2022-03-02 21:18 UTC, dfs- commented
@donho 

It‘s on Windows 11 I guess? I‘ll take a look at it.

2022-03-02 22:17 UTC, donho commented
@dfs- 
Yes, it's Windows 11

2022-03-03 06:03 UTC, dfs- commented
@donho 
Tested the dialog on a newly installed Windows 11 VM and got the following results:

(Windows Scaling: 100%)
![win11findreplacedlg_scale100](https://user-images.githubusercontent.com/6563013/156505703-ef1eb843-c90c-443e-a17a-bef402891f83.png)


(Windows Scaling: 125%)
![win11findreplacedlg_scale125](https://user-images.githubusercontent.com/6563013/156505773-519231f2-c0e6-4034-8993-140696bedac9.png)

Is there anything I am missing? Do you have a setting enabled/disabled, that is not the default. I always test implementations without any additional configurations...

2022-03-03 10:52 UTC, rddim commented
Is it possible to center in horizontal position the switching button and the three dots? Some pixels to the right will be good. Also from the screenshots, windows scaling 125% cut the `newline` text.

2022-03-03 11:17 UTC, dfs- commented
> Is it possible to center in horizontal position the switching button and the three dots? Some pixels to the right will be good.
You mean moving them in the center between the Input fields and the other buttons? Definitely possible but might be irritating as to which part of the dialog they refer. 

> Also from the screenshots, windows scaling 125% cut the `newline` text.
I'll expand the GroupBox a little.

2022-03-03 11:48 UTC, rddim commented
> moving them in the center between the Input fields and the other buttons? 
>
Yes, exactly

> to which part of the dialog they **refer**.
>
You are right, I didn't think from this position. So the 1st ask is not needed :)

2022-03-04 19:51 UTC, dfs- commented
Hi @donho,

I tested the new layout with 150% scaling and can not reproduce your outcome.
![image](https://user-images.githubusercontent.com/6563013/156832080-e872bde8-dce2-421a-ab5f-65b31c9b1a9e.png)

Any advice?

2022-03-05 00:20 UTC, donho commented
@dfs- 
225%

![image](https://user-images.githubusercontent.com/90293/156858817-c8cf572f-9a97-476b-8333-6f7819898ba5.png)

2022-03-05 00:50 UTC, donho commented
@dfs- 

Just did the following modifications:

```diff
-    RTEXT           "&Find what :",IDFINDWHAT_STATIC,1,22,73,8
+    RTEXT           "&Find what :",IDFINDWHAT_STATIC,1,21,73,8^M
     COMBOBOX        IDFINDWHAT,76,20,170,150,CBS_DROPDOWN | CBS_AUTOHSCROLL | WS_TABSTOP
-    RTEXT           "Rep&lace with :",ID_STATICTEXT_REPLACE,1,40,73,8
+    RTEXT           "Rep&lace with :",ID_STATICTEXT_REPLACE,1,39,73,8^M
     COMBOBOX        IDREPLACEWITH,76,38,170,50,CBS_DROPDOWN | CBS_AUTOHSCROLL | WS_TABSTOP
     PUSHBUTTON      "",IDD_FINDREPLACE_SWAP_BUTTON,248,27,16,17
-    RTEXT           "Filter&s :",IDD_FINDINFILES_FILTERS_STATIC,1,58,73,8, SS_NOTIFY
+    RTEXT           "Filter&s :",IDD_FINDINFILES_FILTERS_STATIC,1,57,73,8, SS_NOTIFY^M
     COMBOBOX        IDD_FINDINFILES_FILTERS_COMBO,76,56,170,150,CBS_DROPDOWN | CBS_AUTOHSCROLL | WS_TABSTOP
-    RTEXT           "Dir&ectory :",IDD_FINDINFILES_DIR_STATIC,7,76,41,8
-    COMBOBOX        IDD_FINDINFILES_DIR_COMBO,50,74,196,150,CBS_DROPDOWN | CBS_AUTOHSCROLL | WS_TABSTOP
+    RTEXT           "Dir&ectory :",IDD_FINDINFILES_DIR_STATIC,1,75,73,8^M
+    COMBOBOX        IDD_FINDINFILES_DIR_COMBO, 76,74,170,150,CBS_DROPDOWN | CBS_AUTOHSCROLL | WS_TABSTOP^M

```
and got the result as following:

![image](https://user-images.githubusercontent.com/90293/156860245-87111544-f1d9-4d2a-9633-43b3666dd8e3.png)

If the result of my modifications is acceptable in your scale - please integrate them and the PR will be accepted.

2022-03-05 08:15 UTC, dfs- commented
@donho thanks for the fix, which I implemented as it didn’t seem to break anything.

2022-03-05 10:20 UTC, dfs- commented
GCC doesn‘t like the modifier it seems. I‘ll only be able to have a look in a few hours. If anyone has a smart idea on how to resolve it, please chime in. :)

2022-03-05 23:11 UTC, dfs- commented
I reverted the last two changes. It came to my attention that the problem is not the texts moving downward but rather the comboboxes not scaling in the same factor as other elements. One can notice the "..." button constantly getting bigger than the combobox left to it as scaling increases. Also the comboboxes increase their margin to another.

I am not sure if this is a bug in the operating system but [this Microsofts Dev Community entry](https://developercommunity.visualstudio.com/t/mfc-ownerdraw-combobox-doesnt-respect-dpi-scaling/107468) states it's not.

2022-03-05 23:24 UTC, dfs- commented
@donho - GDI Scaling seems to do the trick (see comment before this one). I took a brief look in some of the dialogs possibly affected by changing the manifest and found no blatant issue.

2022-03-06 01:21 UTC, alankilborn commented
>changing the manifest and found no blatant issue.

The last time the manifest was changed in order to fix problems, it broke more things that it fixed, and was reverted.

2022-03-06 07:35 UTC, dfs- commented
> The last time the manifest was changed in order to fix problems, it broke more things than it fixed, and was reverted.

Quite of destroys my hopes for this whole PR. Nevertheless I found a practical improvement with GDI scaling enabled: starting Notepad++ on a different scaling screen will automatically resize the form to be about the same size as before. Without the GDI scaling it forced itself to have the same amount of pixels horizontally/vertically making it really small especially with my test setup for this PR (4K, 300% scaling)…

2022-03-06 20:31 UTC, Pyre909 commented
Just an fyi the font within the editor is blurry with Directwrite turned on.

Notepad++ v8.3.2   (64-bit)
Build time : Mar  5 2022 - 23:55:04
Path : C:\Users\rr200853\Desktop\npp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1526
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll 

![Capture](https://user-images.githubusercontent.com/3960786/156940986-82942fd4-08f4-49a8-98ec-2e0361ce3e98.PNG)

2022-03-08 18:29 UTC, donho requested changes
1. Please don't use ^M.
2. dpiAware.manifest should not be modified.

2022-03-11 01:20 UTC, donho commented
@dfs- 
Could we close this PR if you have no intention to work on it?

2022-03-11 07:10 UTC, dfs- commented
@donho 
Please bare with me as I am currently on vacation with no Visual Studio at hand. I‘ll be back on Monday. However you can close/reject this PR and I will create a new one.

2022-03-11 11:34 UTC, dfs- commented on PowerEditor/src/ScintillaComponent/FindReplaceDlg.rc
> +    RTEXT           "&Find what :",IDFINDWHAT_STATIC,1,22,73,8^M
Don't quite understand the ^M part, GIT is configured to use core.autocrlf = true as the github doc suggests.

2022-03-11 14:14 UTC, donho commented
@dfs- 
No rush.
Have good holidays then :)

2022-03-11 15:44 UTC, double-standard-you commented
> The result of this PR to me is not nice:
> 
> ![image](https://user-images.githubusercontent.com/90293/156450882-da7e8eca-df2b-489f-b181-de7591dc6bd2.png)

American Shares Truth About Joshua Wong & Hong Kong Democracy
https://www.youtube.com/watch?v=8nXz66Btfl0

American Shares Truth on Xinjiang and Tibet Controversies in China
https://www.youtube.com/watch?v=CldtoYwPtMk

Why is Ukraine the West’s Fault? Featuring John Mearsheimer
https://www.youtube.com/watch?v=JrMiSQAGOS4

Bat coronavirus found in U.S.-funded bio-lab in Ukraine: Russian Defense Ministry
https://www.youtube.com/watch?v=BCydUeHAhzQ

Ukrainians were denied US visas as White House promise help to refugees
https://www.youtube.com/watch?v=BGZhzNFmyhc

Reports of racist treatment against Africans trying to flee Ukraine
https://www.youtube.com/watch?v=JItYOW_uT8s

Fleeing African and Indian students face racism at Ukraine border
https://www.youtube.com/watch?v=ODMOzwI__zs

Canadian RCMP use horses to trample protestors
https://www.youtube.com/watch?v=Usn3CR0E1v0

A bald-faced lie from the Western media corp: Critical “Uyghur Genocide” Questions: A CBC Interview Follow-up
https://www.youtube.com/watch?v=O7IbsPFM2Xg

2022-03-14 18:33 UTC, dfs- commented
@donho 
I opened a new PR #11386 which should replace this one.
I am not closing this PR here right now, since I see a slight chance you dislike the new method and prefer this one.

2022-03-17 15:33 UTC, dfs- commented
New PR was used.

2022-03-17 15:33 UTC, closed without merging