Update french.xml
notepad-plus-plus/notepad-plus-plus pull request #11322
Opened 2022-03-02 09:58 UTC by Mateos81

Upgraded to current english.xml

Notes:
- Some more lines moved
- Added what's missing
- A couple lines removed (6125 and 6127, absent from english file)
- Translated 'bookmark' by 'signet' (else could be 'marque-page' but that's longer)
- Reviewed some lines, especially multi-line dialogs

Exact same line number as english file now!

2022-03-08 13:30 UTC, FdaSilvaYY commented on PowerEditor/installer/nativeLang/french.xml
> +                    <Item id="6871" name="ENTRÉ"/>
typo: "Entrée"

2022-03-08 13:36 UTC, FdaSilvaYY commented on PowerEditor/installer/nativeLang/french.xml
> +            <NbFileToOpenImportantWarning title="Quantité de fichiers à ouvrir trop grande." message="$INT_REPLACE$ fichiers sont sur le point d'être ouverts.
Quantité de fichiers à ouvrir trop grande

2022-03-10 18:39 UTC, donho requested changes
Please check if there's enough room for the modified translation.

2022-03-10 18:39 UTC, donho commented on PowerEditor/installer/nativeLang/french.xml
> +    <Native-Langue name="Français" filename="french.xml" version="8.3">
"C'est écrit en français."
`f` pour moi doit être en minuscule.

2022-03-10 18:39 UTC, donho commented on PowerEditor/installer/nativeLang/french.xml
> +                <Item id="20007" name="Langage utilisateur : "/>
ça depends. Mais ça dépasse, non?
Cela n'a pas été mis à cause du mot "utilisateur" est trop long. 
Vu l'espace qu'on a:

![image](https://user-images.githubusercontent.com/90293/157729611-65ee5022-3c34-4803-b281-f534ea65f73e.png)

Je suis (presque) sûr que ça depasse.

2022-03-10 18:39 UTC, donho commented on PowerEditor/installer/nativeLang/french.xml
> +                    <Item id="6122" name="Cacher la barre des menus (Alt ou F10 pour basculer)"/>
Y-t-il assez d'espace pour tout afficher ?

2022-03-10 21:29 UTC, donho approved these changes

2022-03-10 21:50 UTC, donho commented
I tried to rebase it but have some conflict:

```
$ git rebase -i
Auto-merging PowerEditor/installer/nativeLang/french.xml
CONFLICT (content): Merge conflict in PowerEditor/installer/nativeLang/french.xml
error: could not apply 9a1f54f1... Update french.xml
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 9a1f54f1... Update french.xml

qqq@sssMINGW64 /c/aaa/notepad-plus-plus (master|REBASE 1/8)
```

I was trying to solve but it's quite confusing.

Could you please redo a PR based on current master? Thank you in advance.

2022-03-10 21:50 UTC, closed without merging