Update Bulgarian localization
notepad-plus-plus/notepad-plus-plus pull request #11850
Opened 2022-06-28 15:47 UTC by rddim

* Update localization files · notepad-plus-plus/notepad-plus-plus@2258274 (for `Add an option allows to show only 1 entry per found line in search result` · notepad-plus-plus/notepad-plus-plus@08128ee)

2022-06-28 15:48 UTC, rddim commented
@donho 
There is not enough space for the localization of  string `<Item id="6906" name="Search Result window: show only one entry per found line (not applied to RTL mode)"/>`

![Image-2022-06-28-18-33-38](https://user-images.githubusercontent.com/8998791/176222741-022612c6-146f-4167-b185-fa047a423f10.png)

I can change it to `Прозорец с резултати от търсенето: показване само на един запис на намерен ред (без режим RTL)` which in english is `Search Result window: show only one entry per found line (without RTL mode)`

2022-06-28 16:43 UTC, donho commented
@rddim 
Try to remove the translated word of "Window".

2022-06-28 18:03 UTC, rddim commented
> @rddim Try to remove the translated word of "Window".

@donho 
Done, now everythink fits, thanks

![Image-2022-06-28-21-01-19](https://user-images.githubusercontent.com/8998791/176251646-ab8b3ac0-c72c-4a4c-83e2-fbf718ffc46c.png)

2022-06-30 15:54 UTC, donho requested changes
Please remove the translation of "(not applied to RTL mode)".

2022-06-30 15:54 UTC, donho commented on PowerEditor/installer/nativeLang/bulgarian.xml
> +					<Item id="6906" name="Резултати от търсене: показване само на един запис на намерен ред (не се прилага за режим RTL)"/>
"(not applied to RTL mode)" has been removed in this entry, see: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/059bca3315dbd71fbf235c8bc87eaacbd87a3cec
Sorry for the inconvenience.

2022-07-03 17:26 UTC, rddim commented
@donho 

Done. Sorry for the late reply, I was away from my PC.

2022-07-04 02:59 UTC, donho approved these changes

2022-07-04 03:01 UTC, closed without merging