[WIP] Fix some conversion-null, unused-* warnings
notepad-plus-plus/notepad-plus-plus pull request #12152
Opened 2022-09-12 06:20 UTC by ozone10

fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12151

also add initializers

2022-09-12 06:21 UTC, ozone10 commented on PowerEditor/src/NppCommands.cpp
> +				_mainEditView.execute(SCI_RESETELEMENTCOLOUR, SC_ELEMENT_CARET_LINE_BACK, 0);
For WPARAM and LPARAM prefer "zero" instead of `NULL`. MS documentation is using mostly zero for them.

2022-09-12 06:22 UTC, ozone10 commented on PowerEditor/src/NppNotification.cpp
> +			//static bool prevWasEdit = false;
Should be deleted instead of commented?

2022-09-12 06:22 UTC, ozone10 commented on PowerEditor/src/TinyXml/tinyXmlA/tinyxmlparserA.cpp
> +	//int tabsize = 4;
Should be deleted instead of commented?

2022-09-12 06:22 UTC, ozone10 commented on PowerEditor/src/TinyXml/tinyxmlparser.cpp
> +	//int tabsize = 4;
Should be deleted instead of commented?

2022-09-12 06:22 UTC, ozone10 commented on PowerEditor/src/WinControls/Grid/ShortcutMapper.cpp
> +						//DWORD cmdID = 0;
Should be deleted instead of commented?

2022-09-12 06:23 UTC, ozone10 commented on PowerEditor/src/WinControls/TabBar/TabBar.cpp
> +	//TBHDR nmhdr{};
Should be deleted instead of commented?

2022-09-12 06:24 UTC, ozone10 commented on PowerEditor/src/WinControls/TaskList/TaskListDlg.cpp
> +static HWND hWndServer = nullptr;
Moved from header since it's used only here.

2022-09-12 06:24 UTC, ozone10 commented on PowerEditor/src/localization.cpp
> +	//const int nbControl = 9;
Should be deleted instead of commented?

2022-09-12 06:25 UTC, ozone10 commented on PowerEditor/src/WinControls/FileBrowser/fileBrowser.cpp
> +	TreeView_HitTest(_treeView.getHSelf(), &tvHitInfo);
Return nothing, https://docs.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-treeview_hittest

2022-09-12 06:26 UTC, ozone10 commented on PowerEditor/src/WinControls/ProjectPanel/ProjectPanel.cpp
> +	TreeView_HitTest(_treeView.getHSelf(), &tvHitInfo);
Return nothing, https://docs.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-treeview_hittest

2022-09-12 06:28 UTC, ozone10 commented
@donho 
I have some questions above about deleting code instead of commenting.

2022-09-12 21:23 UTC, donho requested changes
Delete all commented lines of this PR.

2022-09-12 21:23 UTC, donho commented on PowerEditor/src/localization.cpp
> +	//const int nbControl = 9;
Please delete it.

2022-09-12 21:23 UTC, donho commented on PowerEditor/src/Parameters.cpp
> +//size_t getAsciiLenFromBase64Len(size_t base64StrLen)
delete it please.

2022-09-12 21:23 UTC, donho commented on PowerEditor/src/WinControls/Grid/ShortcutMapper.cpp
> +						//DWORD cmdID = 0;
Delete them please

2022-09-13 13:39 UTC, donho approved these changes

2022-09-13 13:43 UTC, closed without merging