Fix conversion-null, nonnull-compare, dangling-else, address warnings
notepad-plus-plus/notepad-plus-plus pull request #12199
Opened 2022-09-19 14:03 UTC by ozone10

, add initializers

fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12198

2022-09-19 14:05 UTC, ozone10 commented on PowerEditor/src/MISC/Common/Common.cpp
> -			&& (buffer != NULL)                                 // check if buffer is not NULL
-Waddress warning: the address of 'buffer' will never be NULL

2022-09-19 14:06 UTC, ozone10 commented on PowerEditor/src/Notepad_plus.cpp
> +					if (text[j] == openingParenthesis[i])
-Wdangling-else warning: `else` belong to innermost `if`

2022-09-19 14:08 UTC, ozone10 commented on PowerEditor/src/Notepad_plus.cpp
> -	if (!this) return;
`this` should never be null. Some compiler even ignore comparing `this` with `NULL`.
If `this` is null then something bad has happened leading  to undefined behavior.

@donho 
I am getting crash even with this check.

2022-09-19 14:09 UTC, ozone10 commented on PowerEditor/src/ScintillaComponent/Buffer.h
> +	bool isUntitled() const { return ((_currentStatus & DOC_UNNAMED) == DOC_UNNAMED); }
warning from MSVC, use bitwise check

2022-09-19 14:11 UTC, ozone10 commented on PowerEditor/src/ScintillaComponent/UserDefineDialog.cpp
> +                        if (!intStr[0])
-Waddress warning: the address of 'intStr' will never be NULL

2022-09-19 14:17 UTC, ozone10 commented
This should be last PR for gcc warnings from me for now.

-Wunknown-pragmas for `#pragma region` might be ignored by later gcc compiler, IIRC there is patch for it

-Wdelete-non-virtual-dtor
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/44811960/job/a7qaamkefci41ynt#L489

I will leave this warning for someone else.

2022-09-19 15:50 UTC, ArkadiuszMichalski commented
@ozone10 
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/44818434/job/kp8yuqnp32yldkxx

For 32-bit this one still exist:
```
PowerEditor/src/ScintillaComponent/SmartHighlighter.cpp: In member function 'void SmartHighlighter::highlightViewWithWord(ScintillaEditView*, const generic_string&)':
PowerEditor/src/ScintillaComponent/SmartHighlighter.cpp:72:21: warning: comparison of integer expressions of different signedness: 'long int' and 'long unsigned int' [-Wsign-compare]
  for (; currentLine < lastLine; ++currentLine)
         ~~~~~~~~~~~~^~~~~~~~~~
```

2022-09-20 02:15 UTC, donho requested changes
Please restore `;` at the end of function definition in header files.

2022-09-20 02:15 UTC, donho commented on PowerEditor/src/ScintillaComponent/Buffer.h
> -	};
I know it's not necessary to add `;`.
But it's just one of Notepad++ coding convention in *.h

2022-09-20 14:16 UTC, donho approved these changes

2022-09-20 14:20 UTC, closed without merging