Fix line hiding issues
notepad-plus-plus/notepad-plus-plus pull request #12250
Opened 2022-09-26 21:36 UTC by Adrian104

This pull request fixes line hiding problems caused by `hideLines()` not working properly.
Fixes #12184 and #8149

2022-09-26 21:51 UTC, Adrian104 commented on PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp
> +			_currentBuffer->setHideLineChanged(false, lineNumber + 1);
Variable `lineNumber` is always decremented before each iteration in this `for` loop, even before `lineNumber >= 0 && !openPresent` evaluates to false. As a result, after this loop `lineNumber` will always be decremented too much by one. To solve this, one is added back to `lineNumber`

2022-09-26 21:58 UTC, Yaron10 commented
@Adrian104,

Both https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12184 and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8149 are fixed. 👍 

Great job! Thank you.

2022-09-27 02:04 UTC, donho requested changes
Please also change the signature of **markerMarginClick** from  `bool markerMarginClick(size_t lineNumber);` to `bool markerMarginClick(intptr_t lineNumber);`

2022-09-27 13:40 UTC, donho approved these changes

2022-09-29 13:33 UTC, closed without merging