Fix for german.xml 8.4.6
notepad-plus-plus/notepad-plus-plus pull request #12307
Opened 2022-10-09 17:32 UTC by schnurlos

Fix sorting of some lines.

2022-10-28 23:32 UTC, donho requested changes
Please check the latest change: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12404

2022-10-28 23:32 UTC, donho commented on PowerEditor/installer/nativeLang/german.xml
> -			<contextMenu-PluginCommands value="Plugin-Befehle" />
Restore this line

2022-11-05 17:08 UTC, schnurlos commented
@donho Done

2022-11-12 10:24 UTC, schnurlos commented
I'm not sure what changes are missing now. Otherwise I can delete this commit and create a new one.

2022-11-20 11:42 UTC, closed without merging

2022-11-20 11:43 UTC, schnurlos commented
Update to 8.4.8