Update friulian.xml cleanup from old entries
notepad-plus-plus/notepad-plus-plus pull request #12322
Opened 2022-10-11 20:02 UTC by conky77

Fix #11561

2022-10-11 20:09 UTC, conky77 commented
@milipili I cleaned up friulian.xlm from old entries. Are you still interested in maintaining the Friulian translation of Notepad++

2022-10-11 20:35 UTC, conky77 commented
I cleaned up the old entries, created the main sections, and I inserted some blank lines to compare the file better with english.xml
Let me know if it is better to remove the blank lines or if it is better to insert the English entries when a translation is missing. What is better to facilitate a new translation?

2022-10-12 12:43 UTC, Mateos81 commented
I believe the PR comment shouldn't contain the "Fix" keyword if other languages are concerned by the matter?

2022-10-16 12:06 UTC, donho commented on PowerEditor/installer/nativeLang/friulian.xml
> +
Why all these blank lines?

2022-10-16 12:11 UTC, donho requested changes
Please fill the blank lines with English original entries - if it's not translatable by you.

2022-10-16 13:57 UTC, conky77 commented
> Please fill the blank lines with English original entries - if it's not translatable by you.

done.

2022-10-27 22:55 UTC, donho commented
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests

2022-10-27 22:55 UTC, closed without merging