Update belarusian.xml
notepad-plus-plus/notepad-plus-plus pull request #12379
Opened 2022-10-22 19:42 UTC by a-polivanchuk

Please update the Belarusian translation from @BORNAME

2022-10-28 17:56 UTC, donho requested changes
Could you please confirm that updated localization file is matched with latest updated english.xml? 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12404

2022-10-28 17:56 UTC, donho commented on PowerEditor/installer/nativeLang/belarusian.xml
> -            <contextMenu-PluginCommands value="Каманды ўбудовы" />
to be restore

2022-10-31 14:19 UTC, a-polivanchuk commented
@donho I've pulled the latest source strings after your request and pushed the related changes in a new commit. Would it be ok for merging? Thanks!

2022-11-01 12:57 UTC, donho approved these changes

2022-11-01 12:59 UTC, closed without merging