Update brazilian_portuguese.xml
notepad-plus-plus/notepad-plus-plus pull request #12516
Opened 2022-11-14 11:16 UTC by Marcello-mco

Mirroring changes for "Add localization for Length label in the Customize Maximum Length popup"

2022-12-03 13:51 UTC, donho commented
@Marcello-mco 
Please add `[xml]` on the beginning of title next time, if the PR is about translation, and only xml file(s) is (are) modified.
Ex: `[xml] Update brazilian_portuguese.xml`

2022-12-15 16:45 UTC, donho commented
@Marcello-mco 
The diff of localization file v8.4.7 vs v8.4.8 is available here: #12649
Please check it and update your localization file, and let me know when this PR is ready to go.
Thank you.

2022-12-15 23:41 UTC, donho requested changes
1. Fix the XML syntax error.
2. Restore unnecessary empty lines changing.

2022-12-15 23:41 UTC, donho commented on PowerEditor/installer/nativeLang/brazilian_portuguese.xml
> +
Please restore all the empty lines (instead of unnecessary white space/TAB).

2022-12-15 23:41 UTC, donho commented on PowerEditor/installer/nativeLang/brazilian_portuguese.xml
> +
Please restore all the following empty lines (instead of unnecessary white space/TAB).

2022-12-15 23:41 UTC, donho commented on PowerEditor/installer/nativeLang/brazilian_portuguese.xml
> +					<Item id="7133" name="Seguir padrão Windows"/>
Restore the format (indentation)

2022-12-16 11:18 UTC, donho requested changes
@Marcello-mco 
There still are some problems for the validation of XML.
The PR cannot be accepted if the XML is invalid.

2022-12-16 11:57 UTC, tarkett2018 commented
@Marcello-mco 
The Problem is line 1375. 
`title="Notepad++ - Fechar sessão no Windows" message="A sessão do Wi` should be `title="Notepad++ - Fechar sessão no Windows" message="A sessão do Wi`. The Character before message= must be a Space.

2022-12-16 12:02 UTC, xomx commented
@Marcello-mco 

![not_a_simple_space_char](https://user-images.githubusercontent.com/13075183/208093681-d7dc4467-c51b-4e50-b811-68c8386b6251.png)

You can Google e.g. for the "strange character Â".

2022-12-16 13:15 UTC, donho approved these changes

2022-12-16 13:17 UTC, closed without merging