Change for Remove Empty Lines command how operate on selection and last empty line
notepad-plus-plus/notepad-plus-plus pull request #12580
Opened 2022-11-28 14:34 UTC by ArkadiuszMichalski

Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12545.

I looked at all operations from `Edit>Line Operations` how they work with and without selection (`Sort`, `Reverse`, `Randomize` and `Remove empty`). And all except (`Remove empty`):
1. Without selection they include the last empty line.
2. With selection they omit the last empty line.
3. For partially selected lines they automatically extend the selection to the entire lines. For sorting it's obvious. But for other cases it also makes sense because we operate on the lines and we do not have to worry about the full (correct) line selecting.

\* `Join lines` command fit only to points 2 and 3 (not work without selection, maybe should).

Taking the above into account, I also made `Remove empty` consistent with this behavior (https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12535/commits/4b5369e8483521c7363c614ed4aa6611505c785c). 

It needs to be clearly stated that these listed sort commands are basically a variant of one command, so other commands should not necessarily behave the same.

This PR is for testing purposes to produce different behavior variants for this `Remove Empty Lines` command.

Continuation of https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12535.

2022-11-28 17:37 UTC, Yaron10 commented
@ArkadiuszMichalski,

👍 
Great work.

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12535#issuecomment-1326817824
> Or...
In real life - is any user going to hold Alt and select column-block for removing empty lines?
I think it's only us testing the various possible cases.

Do you think it's worth the extra code?
It gets more complex. :)

![תמונה](https://user-images.githubusercontent.com/10229320/204342328-495a01d4-1504-45d9-a434-15d68270a0eb.png)

Line 2 is empty.
Alt-select `st`+ part of line 2.
Remove Empty Lines.

Result:
![תמונה](https://user-images.githubusercontent.com/10229320/204342900-9f20ed5f-7b01-4472-9cf3-fca97529fb20.png)

There might be some more cases. Why complicate the code?
I think that "do nothing" on column-selection would be better.

Thank you.

2022-11-28 19:43 UTC, ArkadiuszMichalski commented
@Yaron10 
I'll try to support this column mode in some expected way. If necessary we can easy remove this additional code and do nothing for column mode.

2022-11-28 20:28 UTC, Yaron10 commented
@ArkadiuszMichalski,

As you understand.

Line 2 is still not deleted.

Thanks again.

2022-11-28 22:05 UTC, ArkadiuszMichalski commented
@Yaron10 
>Line 2 is still not deleted.

And it shouldn't be like that? This case can be treated as if the 2nd line has not been selected, because the last empty one cannot be selected? On status bar we have `2x2 -> 2` so in fact nothing has been selected from the second line. 

For such standard selection you also can't delete this last line:
![image](https://user-images.githubusercontent.com/2730894/204390574-7b06b99f-5ddf-4853-891c-44d3f4501a6c.png)
![image](https://user-images.githubusercontent.com/2730894/204390655-1a6ef4e8-7cd4-4063-ae71-f5582bf70a0e.png)

2022-11-28 22:45 UTC, Yaron10 commented
@ArkadiuszMichalski,

> On status bar we have 2x2 -> 2 so in fact nothing has been selected from the second line.

Good point. But you still have `2x2` and you see the selection background.
I know we're entering the extreme-corner-cases/arguments zone. But that's my point: in real life, column-selection would probably be irrelevant to `Remove Empty`.

In the following case, line 1 IS deleted although you have `2x2 -> 2`.
![תמונה](https://user-images.githubusercontent.com/10229320/204396404-589e0b09-b18f-4346-bf62-adcc6befdfc0.png)

And just to make the comparison more accurate, in the following case line 2 is NOT deleted.
![תמונה](https://user-images.githubusercontent.com/10229320/204395700-a39b6c0d-e34c-4e97-80d4-d5e0ee12d9e3.png)

***
I'll continue tomorrow.

2022-11-29 09:40 UTC, ArkadiuszMichalski commented
@Yaron10 
But we in these commands expand the selections first. For column mode it would be equivalent in the form of line selection.
So for your first example it basically means:
![image](https://user-images.githubusercontent.com/2730894/204490793-668b796c-90af-42f2-af6f-e99e0d1fe814.png)
and now we're doing line deletion.

Some more sophisticated column mode support is rather unnecessary for these commands. because there would not be any profit here. These commands delete entire lines, so extending partial selection to entire lines makes sense.

In the second example something is wrong because it should be:
![image](https://user-images.githubusercontent.com/2730894/204490884-ba7e2c49-07b3-4d71-b767-ac13ab730e71.png)

I'll check later why this is happening because even this not work:
![image](https://user-images.githubusercontent.com/2730894/204493907-11012cd2-81f9-4f88-ba82-f97b6add5f6e.png)

2022-11-29 12:38 UTC, ArkadiuszMichalski commented
I'm not insisting, it just worked so far (I don't go into how) so it may continue to work. But it would be easiest to just do nothing for this case.

There is a big difference between normal selection and block selection here. In a normal selection we cannot select the last empty line, but in a block looks like we can.

![image](https://user-images.githubusercontent.com/2730894/204528978-97bc10ea-7056-42dd-be09-534ee0ce35f0.png)
![image](https://user-images.githubusercontent.com/2730894/204529060-0acb9585-fb8a-4fc9-8493-8b6a6dd5a99d.png)

vs

![image](https://user-images.githubusercontent.com/2730894/204529154-36f3dff3-7302-4009-973e-fbf9db7950b9.png)
![image](https://user-images.githubusercontent.com/2730894/204529206-ed01df08-5493-45d1-87b1-254308737d7e.png)

So this complicates the conversion of a block selection into a single one. I'll see if it can be easily fixed with what it is now. I certainly have no intention of adding a new separate ligic to handle block selection here.

2022-11-29 12:59 UTC, alankilborn commented
If you have this:

![image](https://user-images.githubusercontent.com/77065706/204534036-22e2455a-62da-44eb-afe4-5252e8f45f62.png)

or you have this:

![image](https://user-images.githubusercontent.com/77065706/204534135-2696a2da-b6d3-4229-8121-216bf7bf86b3.png)

You get the same result in either case to both SCI_GETSELECTIONSTART and SCI_GETSELECTIONEND.

"Line" 3 in the bottom screenshot is entirely in "virtual space" and thus the "selected" part shown for it really doesn't come into play.

---------------------------------------------------------

>...what the status bar shows

What is shown in the status bar is "contrived".
I wouldn't take the status bar too seriously. :-)

2022-11-29 13:02 UTC, Yaron10 commented
> it just worked so far (I don't go into how) so it may continue to work.

I didn't delve into your code, but it seems you've added quite a few lines for handling column-selection.
If I'm wrong and you can not shorten the code by "do nothing", I'm retracting my comments. :) 

> At least that's what the status bar shows.

It's also what we should assume the user wants to do.
_If we think that any user is going to hold Alt and column-select for removing empty lines._

> I'll see if it can be easily fixed with what it is now. I certainly have no intention of adding a new separate ligic to handle block selection here.

👍

2022-11-29 13:07 UTC, alankilborn commented
>You get the same result in either case to both SCI_GETSELECTIONSTART and SCI_GETSELECTIONEND.

Since this is true, can't the selection type when the user runs the command be mostly ignored?
It should work if using those two Scintilla commands (which are then expanded to "whole line" positions).

So the only case it should not handle is multiple stream selections?  In that case it would only operate on the "main" selection's lines?

It should handle fully, for no special coding:

* single stream selection
* thin column selection (zero width)
* rectangular column selection (non-zero width)

2022-11-29 13:08 UTC, Yaron10 commented
@alankilborn,

Welcome back. :)

Do you agree that processing column-selection or "do nothing" should be determined by the "shorter-code" factor?

2022-11-29 13:34 UTC, alankilborn commented
>Welcome back.

Sorry for popping in/out.  I just don't always have time to fully contribute...

>agree that processing column-selection or "do nothing" should be determined by the "shorter-code" factor.

That seems reasonable, although from my earlier comments I don't see why column/thin selection would require any specialized coding.

2022-11-29 17:59 UTC, ArkadiuszMichalski commented
@alankilborn 
>You get the same result in either case to both SCI_GETSELECTIONSTART and SCI_GETSELECTIONEND.

But here is important how we obtain the first and last lines, directly from this points or use `getSelectionLinesRange()`, which makes some correction.

@Yaron10 
>I didn't delve into your code, but it seems you've added quite a few lines for handling column-selection.
If I'm wrong and you can not shorten the code by "do nothing", I'm retracting my comments. :)

These are still just additional conditions. It's easy to remove if needed.

>And as I wrote earlier:
>>I didn't delve into your code, but it seems you've added quite a few lines for handling column-selection.
If I'm wrong and you can not shorten the code by "do nothing", I'm retracting my comments.

Column selection has one additional advantage over standard selection, if we want to remove the last empty line too then we can do that, same as for the entire document. For standard selection this is impossible because it cannot be selected (of course I'm skipping the solution of removing the EOL from the previous line).

So:
![image](https://user-images.githubusercontent.com/2730894/204606080-62cf8fb0-f30d-49ed-8fca-dd484998e8ff.png)
will not remove line 2.
but:
![image](https://user-images.githubusercontent.com/2730894/204606194-452c88a7-6b0a-488a-9d93-9ac233dc4c66.png)
will remove line 2.

You can check the last PR to see if its behavior is more appropriate.

2022-11-29 20:49 UTC, Yaron10 commented
@ArkadiuszMichalski,

I appreciate your perseverance.
**If you don't want me to further comment about column-selection, please let me know. :)**

In the last commit there are ~15 lines for handling column-selection.
If it can't be implemented as @alankilborn suggested, why not return at the beginning? 
```
if (isRecSel)
   return;
```

> Column selection has one additional advantage over standard selection...

That's a nice point. But is it worth it?

And I've encountered some more issues.
***
![תמונה](https://user-images.githubusercontent.com/10229320/204642305-4a75a127-456d-4485-a5b0-776a00865357.png)

Remove Empty Lines.

Result:
![תמונה](https://user-images.githubusercontent.com/10229320/204642480-59a3cefe-afe8-407e-967e-811b66daef24.png)

Expected:
3 lines only.
***
![תמונה](https://user-images.githubusercontent.com/10229320/204642726-3d9e9880-47a0-48c0-8ba2-33b16236af5d.png)

Remove Empty Lines.

Result:
![תמונה](https://user-images.githubusercontent.com/10229320/204642957-bad660a9-04b5-4406-8581-ecfb3b81bb90.png)

2022-11-29 21:02 UTC, alankilborn commented
>If it can't be implemented as @alankilborn suggested

My suggestion doesn't "fit" as @ArkadiuszMichalski wants to use:

>getSelectionLinesRange(), which makes some correction

And I suppose that makes sense.

-------------------------------------------

Perhaps doing nothing on any type of column selection (thin or not) is best.
Be careful if trapping out column-selection, it is not as simple as testing for SCI_SELECTIONISRECTANGLE.

2022-11-29 21:17 UTC, Yaron10 commented
@alankilborn,

Thank you for the clarification and for the additional info.
Is the term "Encyclopedia" still used these days? :)

2022-11-30 00:27 UTC, ArkadiuszMichalski commented
>@alankilborn
>You get the same result in either case to both SCI_GETSELECTIONSTART and SCI_GETSELECTIONEND.
>Since this is true, can't the selection type when the user runs the command be mostly ignored?
>It should work if using those two Scintilla commands (which are then expanded to "whole line" positions).
>It should handle fully, for no special coding:
>single stream selection
>thin column selection (zero width)
>rectangular column selection (non-zero width)

And it might even be so if it wasn't for the fact that it's not entirely consistent with what the status bar shows. And let me remind you that it didn't bother me at the beginning :)

@Yaron10
>If it can't be implemented as @alankilborn suggested, why not return at the beginning?
```
if (isRecSel)
   return;
```

I wrote that for this case (column mode) is simplest to do nothing, but this always can be achieved by adding the above at the beginning (and clean up rest). The same basically applies to multiselections, because it doesn't support this mode anyway.

I will experiment with this column mode to make it work as expected (even in line with bar status). But that doesn't mean it will be accepted in the end.

@Yaron10 
Try the last PR. I wonder if you'll find anything else :)

2022-11-30 12:02 UTC, alankilborn commented
>But that doesn't mean it will be accepted in the end.

Yep, I've often thought that over-thinking (and over-discussing) a feature makes Don quick to pick up his REJECT stamp.  :-)

2022-11-30 12:56 UTC, Yaron10 commented
@ArkadiuszMichalski,

> I wonder if you'll find anything else.

The last commit seems very good.
But "I'll be back" (with the correct accent :) ).

I'll be back late this evening and have another look.
Anyway, I still think that column-selection would not be useful in real life.

Thank you for your work.

2022-12-01 00:58 UTC, Yaron10 commented
@ArkadiuszMichalski,

The final implementation seems very good and solid.  👍 
I must mention again that I'm impressed by your patience and persistence. :)

Thank you.

@alankilborn,

Thank you too for your patience and very helpful comments. 👍

2022-12-02 14:31 UTC, donho commented
@ArkadiuszMichalski
> This PR is for testing purposes to produce different behavior variants for this `Remove Empty Lines` command.

So it's not for merging, is it?

2022-12-02 23:19 UTC, ArkadiuszMichalski commented
@donho 

Last commit can be considered to merging. All reported issues have been fixed. In short new behavior looks like this:
1. For partially selected lines they automatically extend the selection to the entire lines.
2. If nothing has been removed then the original selection is restored (before expand).
3. For selection the last empty line is treat in a consistent way (with what we see visually and what the status bar shows).
4. It works fine for rectangular selection.

So now it works consistently. But if any of the above changes are not accepted then can be removed. Based on the behavior established here the other line methods can be corrected to work similarly. But we must have at least one reference method of how it should look like.

2022-12-06 14:57 UTC, donho commented
I have no opinion about column mode, though I agree that we can just not do the remove empty lines operation when column mode is detected (as a lazy dev). But since it (column mode) is treated correctly, I've got nothing to say about it.

OTOH, the last blank line is (almost) impossible to be removed, except without selection (entire doc mode).
Is it a normal behaviour (Ctrl-A + empty lines operation) for users?

2022-12-06 15:02 UTC, donho requested changes
Please consider the following remark.
~~Maybe redefine the last blank line with selection behaviour.~~
*Edit: last blank line with selection behaviour in this PR is a regression to me.*
*Please restore the current behaviour of last blank line with selection.*

2022-12-07 00:15 UTC, donho commented
@Yaron10 
Sorry I don't quite understand your understanding of what I say, let me make it more clear:

In this PR, the last blank line can be removed only in entire doc mode (No selection).
It's a regression to me because in the current version v8.4.7
* Ctrl-A + empty lines operation : remove the last blank line
* Manually selecting from 0 to the last 2 bytes CRLF  + empty lines operation : remove the last blank line
* Select last 2 bytes CRLF  + empty lines operation : remove the last blank line

2022-12-07 01:37 UTC, Yaron10 commented
@donho,

![תמונה](https://user-images.githubusercontent.com/10229320/206063134-03c198b4-9937-46bf-8f63-18e533e103a2.png)

Line 2 is blank.
Ctrl+A.

See the status bar:
![תמונה](https://user-images.githubusercontent.com/10229320/206063760-a92bf634-5dfa-4329-8b49-8b86ceca9f70.png)

You have 2 lines.
You've **selected all**.
Selected lines: **1**.

Is that correct?
If you think the current status bar implementation (**and the concept behind it**) is correct, then we can NOT treat the second line as selected.
"Select All" means select all that can be selected. And an empty line can not be selected.

The `Remove Empty Lines` code was written before the selection-concept changed, and was never updated.
Other operations (e.g. Sort) have been updated, and this PR is updating the `Remove Empty` operation and fixing the inconsistent behavior in v8.4.7.

2022-12-07 01:51 UTC, donho commented
@Yaron10 
I see your arguments. And I do understand them from the viewpoint of dev.
However in the shoes of users, when all the document is selected, and empty lines operation is applied, I would surprise about the last blank line is still there. The current behaviour for me is correct, if the PR was merged as it is, then there would be a regression, and people would be complain.

Regarding the info shown on status bar - I would say it's correct also, because it reflects graphically the selection, from the viewpoint of user. The 2 functions are not associated necessarily.

2022-12-07 02:15 UTC, donho commented
> That is: on Ctrl+A the line is excluded, whereas if nothing is selected - that line is included

Ctrl+A & nothing is selected should have the same behaviour - last line get removed.

2022-12-07 02:19 UTC, Yaron10 commented
I respectfully disagree. But it's your code.

2022-12-07 02:23 UTC, Yaron10 commented
Don,

Before making the final decision, please let @alankilborn and @ArkadiuszMichalski chime in.
They might convince you. :)

I must retire now.

2022-12-07 02:23 UTC, donho commented
@Yaron10 
Thank you for your suggestion!

2022-12-07 03:32 UTC, alankilborn commented
> Ctrl+A & nothing is selected should have the same behaviour

I agree with this.  (Sorry Yaron10.)
@donho, is this a global statement?  Meaning for ALL commands?  I think so, and hope you agree.

2022-12-07 11:51 UTC, ArkadiuszMichalski commented
@donho 

At some point someone changed the behavior for selection and last blank line.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5867025842a45b4793e068684accb5a22fb5d3d0/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L2898
```
		// if the end of the selection includes the line-ending, 
		// then don't include the following line in the range
```

Wherever the `getSelectionLinesRange()` method is used, the last blank line is ignored. This includes, for example, what the status bar shows and working for all sorting methods. Invoking these methods with no selection or all selection (Ctrl+A) has a different effect. Let me just remind once again that this is not some weirdness at all, I saw the same thing in Sublime Text for sorting.
This was probably some prelude to unifying this behavior everywhere, but it was only done for sorting methods.

From the perspective of a standard user this is what we see visually (visually this last blank line is not selectable in a standard way). 
![image](https://user-images.githubusercontent.com/2730894/206150444-f9ffd156-dfd4-44cf-9619-3457db690c60.png)
![image](https://user-images.githubusercontent.com/2730894/206150562-f1afd8e7-d0af-4731-bada-8e51b74344b5.png)
Of course, I omit the fact that the EOL in the 4th line is responsible for the appearance of the 5th line, but the standard user does not need to know what EOL is.
![image](https://user-images.githubusercontent.com/2730894/206150703-bf0585c3-5139-47d5-bc2f-240bcab5ee4f.png)
![image](https://user-images.githubusercontent.com/2730894/206150562-f1afd8e7-d0af-4731-bada-8e51b74344b5.png)

No matter how I look at it, I selected 4 lines here, 3 are empty (2,3,4) and only those line are deleted, which is true. I'm not arguing that because that's what I see on screen.

>OTOH, the last blank line is (almost) impossible to be removed, except without selection (entire doc mode).
Is it a normal behavior (Ctrl-A + empty lines operation) for users?

It can be selected by column selection, which is exactly in line with the visual presentation:
![image](https://user-images.githubusercontent.com/2730894/206151833-ac3a4c12-837a-4b16-b877-592951f18a85.png)
![image](https://user-images.githubusercontent.com/2730894/206152162-076e7f64-f40a-41a6-9f9a-5f0745081855.png)
or even:
![image](https://user-images.githubusercontent.com/2730894/206152289-59f425e3-6b7e-4bef-972a-8d89175eb9ee.png)
![image](https://user-images.githubusercontent.com/2730894/206159758-0cf8bdc4-eaac-46b0-9dc7-99d4da6f6bec.png)

In the above I really see that this last blank line is part of selection.

**Due of how to treat this last blank line this PR and discussion is so long.** 


If Ctrl+A must be the same as no selection, what about the situation when we selecting something from the end?
![image](https://user-images.githubusercontent.com/2730894/206153476-530173ce-a87c-46d5-ab44-219f0f6e1f31.png)
I've selected line 3 and 4 and because of autoexpand this line will be removed (on this PR).  What should be done after reverting behavior, select 3-4 or 3-5 (assuming we keep the autoexpand)?

Same question for this:
![image](https://user-images.githubusercontent.com/2730894/206154360-2828fbae-9d48-4142-89ab-9e74c82f2215.png)
![image](https://user-images.githubusercontent.com/2730894/206156567-d0fbb4dd-be2b-4f18-b006-631ac4e0247a.png)
or
![image](https://user-images.githubusercontent.com/2730894/206155605-1680419f-ec6e-4e95-ae3d-034cc96f8843.png)
![image](https://user-images.githubusercontent.com/2730894/206156292-9a3d2a91-4225-4f67-9cea-0ac432a76385.png)

Visually, I only select 2 lines (3-4), but if I have to restore the previous behavior, what should happen here?

In general, if we assume that a standard selection (full or partial from the end) can cover the last blank line, it probably doesn't make sense to make any changes and complicate the whole thing. If someone wants to remove the last blank line it should make selection including last EOL in document himself. The current implementation works according to this approach, even with block selection (at least for these two methods).

I will release one more commit with the fixes suggested by Don. If in the future the behavior for the last blank line will changed, there will already be some base code for further work.

2022-12-07 12:44 UTC, donho commented
@alankilborn 
> @donho, is this a global statement? Meaning for ALL commands? I think so, and hope you agree.

If you mean all Line Operations should have the same behaviour to process the last blank line, my reply is: yes, they should have, and it's better that they treat the last blank line in order to keep the consistency - for the reason that all lines are treated, but not for aligning the behaviour with other Line Operations.

OTOH the last blank line have the different visibility in the different Line Operations, in the eyes of users.
In "Remove Empty Lines", users focus on removing the empty lines - so while he/she selects the whole document (mouse selection or Ctrl-A), applies "Remove Empty Lines", and find the last blank line is still there - it's a bug.

For "Lines sort" operations or other ones ("Remove Duplicated Lines", "Join Lines", "Reverse Line Order"...), however, it's another story. A lot of people don't notice or even don't care of the fact that the last blank line is excluded in the operations. As the last non-empty line is processed, it doesn't matter for them.

So here is my opinion about make all Line Operations consistent: If one of you want to "align" the behaviour of all Line Operations, the last blank line should be included, but not excluded. From my side, I will make sure the PR is simple and no risk of regression, to decide if the PR is accepted - after all, it's rather BETTER TO HAVE than MUST HAVE feature.

2022-12-07 14:57 UTC, Yaron10 commented
@alankilborn,

> I agree with this. (Sorry Yaron10.)

No need to be sorry. :)
There's an old saying (loosely translated): "Just as people's faces are not the same, so their opinions are not the same".

Unlike Don, you think that the last empty line should be excluded even if nothing is selected.

***
![תמונה](https://user-images.githubusercontent.com/10229320/206210640-7e10d160-d967-42f2-9ff6-41171856993c.png)

If we could differentiate between Ctrl+A  and selecting the first line only, I'd agree Ctrl+A should be treated as "entire doc".

An example for Select All:
![תמונה](https://user-images.githubusercontent.com/10229320/206211419-ce561bdb-a262-4d68-9563-1d7513d64382.png)

But we can not make that distinction, and therefore I think the commands should be in-sync with the visual selection and the status bar.

Thank you all.

2022-12-07 15:28 UTC, donho commented
@ArkadiuszMichalski 


> Wherever the getSelectionLinesRange() method is used, the last blank line is ignored. This includes, for example, what the status bar shows and working for all sorting methods. Invoking these methods with no selection or all selection (Ctrl+A) has a different effect.

`getSelectionLinesRange() `might be modified for other Line Operations, to meet BETTER TO HAVE behaviour (the last blank line included). But here we are talking about "Remove Empty Lines".

> Let me just remind once again that this is not some weirdness at all, I saw the same thing in Sublime Text for sorting.
This was probably some prelude to unifying this behavior everywhere, but it was only done for sorting methods.

I believe that Sublime Text is a good editor, however what I'm looking for is not other editor's behaviour, but the feeling of an editor user: One want to remove all the empty lines of his/her document, after select all and execute the command in question, the last blank line is not removed. It's no doubt a bug. Since the current behaviour is correct (I don't see any repport for "Remove Empty Lines" operation's bad behaviour), acceptance of this PR as such will insert a regression.

> It can be selected by column selection, which is exactly in line with the visual presentation:
...
or even:
...
In the above I really see that this last blank line is part of selection.

True. I appreciate this PR for its selection part (persistent selection after operation and column selection).
But if the last 2 bytes of document are CRLF and they're selected with normal selection mode, the last line should be treated by "Remove Empty Lines" operation. It makes sense to me.  

> I've selected line 3 and 4 and because of autoexpand this line will be removed (on this PR). What should be done after reverting behavior, select 3-4 or 3-5 (assuming we keep the autoexpand)?
Same question for this
...
or
...
Visually, I only select 2 lines (3-4), but if I have to restore the previous behavior, what should happen here?

The "autoexpand" you are talking about is the selection after the "Remove Empty Lines" operation, right? If it is, I would say, if the last line which contains CRLF, the select the last 2 bytes CRLF:

![image](https://user-images.githubusercontent.com/90293/206218370-1d8ab7ea-2e02-4a6e-9564-1994ec3fe891.png)


Otherwise

![image](https://user-images.githubusercontent.com/90293/206217828-f67fbe59-3855-4c3c-9b08-782d1953a599.png)


> If someone wants to remove the last blank line it should make selection including last EOL in document himself. The current implementation works according to this approach, even with block selection (at least for these two methods).

I agree. However, in current PR, the last blank line can be removed only no selection, and column selection (which I omitted, sorry).
What it should be is besides above 2 cases, plus Select All & select the 2 last bytes CRLF:
![image](https://user-images.githubusercontent.com/90293/206220185-10558f8e-d376-40bb-9832-858419871cf8.png)

2022-12-07 15:42 UTC, Yaron10 commented
@donho,

> But if the last 2 bytes of document are CRLF and they're selected with normal selection mode, the last line should be treated by "Remove Empty Lines" operation. It makes sense to me.

![תמונה](https://user-images.githubusercontent.com/10229320/206223447-f7d00360-cda8-466a-a6e8-01e32d904905.png)

Should line 3 be removed in this case?

2022-12-07 16:15 UTC, donho commented
> And in v8.4.7 the user has no way to _exclude_ the last empty line.

It's not true. Select in this way, the last blank line is kept, under v8.4.7

![image](https://user-images.githubusercontent.com/90293/206232035-92f2daa0-7a1a-4af2-8f01-e3544f04f35d.png)

2022-12-07 16:38 UTC, Yaron10 commented
![תמונה](https://user-images.githubusercontent.com/10229320/206232898-40e3d9a5-7014-4ad4-a24c-6bc70daf13ff.png)

Let's try to put aside Ctrl+A.
The user has manually selected the first 2 lines. Why should line 3 be removed in this case? What's the difference?
Why should we care about the content of the line after the selection?

> It's not true. Select in this way, the last blank line is kept, under v8.4.7

You're right.
I had in mind another part of this PR which expands partially selected lines.

2022-12-07 16:54 UTC, donho commented
> Why should we care about the content of the line after the selection?

Sorry, don't follow you.


> Let's try to put aside Ctrl+A.
> The user has manually selected the first 2 lines. Why should line 3 be removed in this case? What's the difference?

The cursor cross the 2nd line to the 3rd line:

![image](https://user-images.githubusercontent.com/90293/206240444-e0a9f118-c520-4fa6-b8af-9aee78f18397.png)

2022-12-07 17:13 UTC, Yaron10 commented
> Why should we care about the content of the line after the selection?
>> Sorry, don't follow you.

Let's look at the following 2 cases:

![תמונה](https://user-images.githubusercontent.com/10229320/206242759-ca01205e-7ac4-4629-b0a9-1fb172c6643b.png)

![תמונה](https://user-images.githubusercontent.com/10229320/206242847-4532e01b-e923-42f9-b262-f3cb5ee03916.png)

Why should the CRLF in line 3 (in the first case) make us _exclude_ that line, and the lack of CRLF in line 3 (in the second case) make us _include_ that line?

> The cursor crosses the 2nd line to the 3rd line:

But the caret is on the line after the selection _in both case_.
Also - when the status bar implementation changed, the idea/concept was that we don't care about the caret being on the following line.

2022-12-07 20:34 UTC, Yaron10 commented
@donho,

And as I've mentioned: different opinions are a fundamental part of the human nature.

@ArkadiuszMichalski,

Sorry for the extra work.

2022-12-08 01:22 UTC, ArkadiuszMichalski commented
@donho 
>The "autoexpand" you are talking about is the selection after the "Remove Empty Lines" operation, right?

Yes, right after invoking the method, but before deleting anything. We operate on the (whole) lines so with autoexpand selection we don't have to worry about the full (correct) line selecting. 

The current implementation is buggy anyway:
![image](https://user-images.githubusercontent.com/2730894/206315790-2c0f6ddb-bd4e-44c7-9ec1-895595338f38.png)
We select 5 and 6 line and last CRLF (so also line 7 if we assuming that's the way it should be), but after invoking the second command we get:
![image](https://user-images.githubusercontent.com/2730894/206316058-56d99349-e3fa-4557-a2c0-60b666a80a08.png)
So two line was removed (not three). We would also need to select CRLF on line 4 to get such behavior:
![image](https://user-images.githubusercontent.com/2730894/206317945-fe23aa1b-7cf8-4592-a6be-171090ca67bb.png)
Effect:
![image](https://user-images.githubusercontent.com/2730894/206318105-c0f73052-2e84-415b-95ba-f8aa0d616ab6.png)
Still possible, but completely unintuitive.


To try to keep the current behavior (Ctrl+A and weird last CRLF handling) it might look like this:
1.
![image](https://user-images.githubusercontent.com/2730894/206316960-38fe976d-d9da-4dcd-8f33-036d73c8a922.png)
Stretching to something other than the last blank line must also contain `CRLF` because that's how first regex works. When we do it manually, it's also looks like this. So this CRLF is considered as part of the line it appears in. So after all line 2 and 3 will be removed.
2. Let's play with last line:
![image](https://user-images.githubusercontent.com/2730894/206318497-a3dfaf39-d495-406a-ad17-4a34c3f2e0d3.png)
If someone didn't explicitly select the last CRLF, we stretch without it. Lines 5 and 6 will be deleted here.

But if the last CRLF was selected:
![image](https://user-images.githubusercontent.com/2730894/206318897-e977257d-f7b0-4377-857f-8b500482bee2.png)
we also do the stretching of the five line. But in this case lines 5,6 and 7 are removed.

Either way, the questions will continue to arise, what in this situation?
![image](https://user-images.githubusercontent.com/2730894/206321257-ff0908e1-19f3-4b0c-b1de-dd2ba8e9d788.png)
I don't know if someone here wants to remove only line 7 or 6-7? Probably 6-7 because for 7 only CRLF should be selected.

What about this?
![image](https://user-images.githubusercontent.com/2730894/206331899-2dbaf421-4513-49ef-9eb2-f1d8e875466e.png)
Line 2-3 should be removed or only 3? For me should be 2-3 (this is not the last CRLF and should not be treated differently, it sit on line 2 so that line will be automatically selected).

2022-12-09 00:52 UTC, donho commented
@ArkadiuszMichalski 
What's the initial intention of this PR then?

2022-12-11 01:55 UTC, ArkadiuszMichalski commented
After all the current code is short and does the job. Sometimes we need to experiment with correct selecting CRLF in lines to achieve the desired result. It makes no sense to complicate this process.

2022-12-11 01:55 UTC, closed without merging

2022-12-11 13:44 UTC, donho commented
@ArkadiuszMichalski 
Thank you for your effort !