Support selection for EOL commands
notepad-plus-plus/notepad-plus-plus pull request #12711
Opened 2022-12-27 09:21 UTC by ArkadiuszMichalski

Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12702.

2022-12-27 14:55 UTC, Yaron10 commented on PowerEditor/src/Notepad_plus.cpp
> +	bool isEntireDoc = _pEditView->execute(SCI_GETANCHOR) == _pEditView->execute(SCI_GETCURRENTPOS);
Just curious: is there a reason not to use the previous common code?
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/31a392ae59e1dc3494c4193e7a3df3e4e34f3a5e/PowerEditor/src/Notepad_plus.cpp#L1561

A new function `getMainSelectionLenght()` could be used in most cases.

2022-12-27 14:59 UTC, Yaron10 commented on PowerEditor/src/Notepad_plus.cpp
> +	isEntireDoc ? _pEditView->execute(SCI_TARGETWHOLEDOCUMENT) : _pEditView->execute(SCI_TARGETFROMSELECTION);
Could also be:
`_pEditView->execute(isEntireDoc ? SCI_TARGETWHOLEDOCUMENT : SCI_TARGETFROMSELECTION);`

2022-12-27 20:12 UTC, Yaron10 commented
![תמונה](https://user-images.githubusercontent.com/10229320/209717297-b1099ea3-2679-4eb9-a7f8-3cba6a1e1e4f.png)

`EOL to Space`:
No change.

`Remove Unnecessary Blank and EOL`:
![תמונה](https://user-images.githubusercontent.com/10229320/209717492-725efef0-5a7a-49f2-83ba-f0065b575aa0.png)

Isn't that confusing?

2022-12-28 09:26 UTC, ArkadiuszMichalski commented
@Yaron10 

Name `Remove Unnecessary Blank and EOL` is wrong https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12702#issuecomment-1365705873, it's more like `Trim both and EOL to Space` or `Trim all and EOL to Space`, but `EOL to Space` is also wrong, it's more like join lines.

`SCI_LINESJOIN` not work on column selection, If we don't expand such selection to lines it will not work, but @donho don't want expand for `EOL to Space` https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12702#issuecomment-1365144908. Here, this expanding does not affect the modified data anyway, so it may be worth doing it so that both of these commands work consistently (along with Trim).

2022-12-28 14:22 UTC, donho commented
> Name `Remove Unnecessary Blank and EOL` is wrong [#12702 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12702#issuecomment-1365705873), it's more like `Trim both and EOL to Space` or `Trim all and EOL to Space`, but `EOL to Space` is also wrong, it's more like join lines.

How about "Trim All and Join Lines" ?

2022-12-28 15:47 UTC, Yaron10 commented
> Possible solution:
>
  >  expand block selection to standard selection for EOL to Space
    return for Remove Unnecessary Blank and EOL when detect block selection
    don't support block selection at all (for Trim and above two commands), just return.

> I thought it's not necessary. But if it could help the consistency, OK for expanding.

👍 

I would expand stream selections, and "don't support block selection at all" if it should shorten the code.

***

> How about:
>
>    Remove EOL to Space command. (It's redundant with Join Lines).
    Rename Remove Unnecessary Blank and EOL to Trim Both and Join Lines. ?

👍

2022-12-28 22:38 UTC, ArkadiuszMichalski commented
@donho 
I add autoexpand selection for partially selected lines for `EOL to Space` so this will fix Yaron example.

I checked more closely how `EOL to Space` and `Join Lines` commands works until now and they have some differences:
- `EOL to Space` always replace (or remove) the selected EOLs:
![image](https://user-images.githubusercontent.com/2730894/209866065-ba9fee27-9250-409e-ad77-636e82652722.png)
So here we visually select 2 lines (1,2), but in fact 3 lines was joined (1,2,3).

    `Join Lines` make some correction if nothing is selected on last line, so selected EOLs might change:
![image](https://user-images.githubusercontent.com/2730894/209866733-9d753e81-31f9-421f-a362-a26f77a5350f.png)
So here we visually select 2 lines (1,2) and 2 lines was joined (1,2).

- due to the above behavior also selecting everything works differently
`EOL to Space`
![image](https://user-images.githubusercontent.com/2730894/209867981-f1617d01-5c6e-4e12-8021-99961de566ab.png)
So here all lines was joined (1,2,3,4). If we want omit 4 line we should skip last EOL in selection:
![image](https://user-images.githubusercontent.com/2730894/209868188-6b9eb4da-abbf-4cb1-817d-ff46344fb119.png)
`Join Lines` always skip last EOL so if it was such EOL then the empty line will always be there:
![image](https://user-images.githubusercontent.com/2730894/209868475-319fe8f1-51ff-4e5c-9bb4-3e9b5f3b5bc7.png)
So here we visually select 3 lines (1,2,3) and 3 line was joined (1,2,3). It is not possible to join all lines into one here (last empty line will always stay).

So:
`EOL to Space` - does not strictly replace every EOL to space. If it's not needed it's just removed it. 
![image](https://user-images.githubusercontent.com/2730894/209642344-263c29be-11ce-4799-8dc4-e9fa95f1d883.png)
We still have one space (not two). If someone really wants to replace every EOL to space they can use Find/Replace dialog.
Actually `EOL to Space` command also not work like `Join Lines` command. In addition to the above differences `Join Lines` also not work without any selection (we need press `Ctrl+A`).
`EOL to Space` seems to be more flexible than `Join Lines` because we have more control what we select. I don't know if there's a better name for this behavior than `EOL to Space`, but if there isn't, it's best not to change it.

Maybe preserve `EOL to Space` command? It's been around for a long time and no one has reported it. Changing name `Remove Unnecessary Blank and EOL` to `Trim both and EOL to Space` would be more clear that it's a combination of these two commands.  

If someone need `Trim both and Join Lines` then always can record such macro with `Trim Leading/Trailing` + `Join Lines` commands.

The last commit doesn't change the existing behavior without selection (all works the same). I only added selection support.

But if `EOL to Space` should be removed and rename `Remove Unnecessary Blank and EOL` to `Trim Both and Join Lines` then how `Join Lines` should behave? Exactly like now what I show in above picture, or something should be tweak also for this command?

2022-12-29 00:23 UTC, Yaron10 commented
@ArkadiuszMichalski,

> I checked more closely how EOL to Space and Join Lines commands works until now and they have some differences...

Very nice! 👍 

> In addition to the above differences Join Lines also not work without any selection (we need press Ctrl+A).

I thought that was next on your list. :)
It seems necessary now. 

And I think that without selection, the last empty line should be removed as well.

***

> I add autoexpand selection for partially selected lines for EOL to Space so this will fix Yaron example.

![תמונה](https://user-images.githubusercontent.com/10229320/209886743-1e216db5-26fd-4570-87f1-4c899d600393.png)

`EOL to Space`:
![תמונה](https://user-images.githubusercontent.com/10229320/209886811-1e752f91-ad5f-418f-a826-828c7a96b78a.png)

IMO it does not make sense to  remove the EOL of line 1 only. What's the difference between line 1 and line 2?
I thought Don agreed with that.

If that's the case, `EOL to Space` should include partially _stream-selected_ lines as well.
This may be useful and expected in real-life: the user might select lines from the editor (i.e. not from the Lines Margin), and not notice that the last EOL (in the selected lines) was actually not selected.

![תמונה](https://user-images.githubusercontent.com/10229320/209887645-da96fb3d-6583-47bf-8ae6-3826c5e5b2d6.png)

2022-12-29 02:08 UTC, ArkadiuszMichalski commented
From such picture It's hard to guess what you're doing here:
![image](https://user-images.githubusercontent.com/10229320/209886743-1e216db5-26fd-4570-87f1-4c899d600393.png)

>IMO it does not make sense to remove the EOL of line 1 only. What's the difference between line 1 and line 2?

If you want to remove both then you have to explicitly indicate it:
![image](https://user-images.githubusercontent.com/2730894/209892318-92af7c3b-49c5-4096-842a-987bbd43f39d.png)

How expanding lines we established in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12655#issuecomment-1358749687. Currently this expanding was done only for block selection to work (because Trim supports it so let works also here). But we don't select more EOL's from what has been selected by user. Without expanding this will also works for standard selection, but still only on selected EOLs, so nothing was changes here.

2022-12-29 14:39 UTC, Yaron10 commented
@ArkadiuszMichalski,

> From such picture It's hard to guess what you're doing here:

You're right.

Column selection.
![תמונה](https://user-images.githubusercontent.com/10229320/209967460-abda3a0e-eaac-4056-bc3e-ca0d547f1b5e.png)

Why is line 4 "more selected" than line 5? And if the user starts the selection from the bottom up?

@donho,

What do you think?

2022-12-29 16:01 UTC, donho commented
@ArkadiuszMichalski 
> Maybe preserve EOL to Space command? It's been around for a long time and no one has reported it. Changing name Remove Unnecessary Blank and EOL to Trim both and EOL to Space would be more clear that it's a combination of these two commands.

The points are accepted.
Let's preserve EOL to Space command and changing name "Remove Unnecessary Blank and EOL" to "Trim both and EOL to Space". 

@Yaron10 
> Why is line 4 "more selected" than line 5?

Sorry, I don't follow you?

> And if the user starts the selection from the bottom up?

From bottom up or not, it's strange to me that EOL are replaced while the column selection being not on CRLF.

@ArkadiuszMichalski 
I'm finally for `don't support block selection at all (for Trim and above two commands), just return.`

2022-12-29 16:29 UTC, Yaron10 commented
@donho,

> I'm finally for don't support block selection at all (for Trim and above two commands), just return.

👍 

> Sorry, I don't follow you?

It's irrelevant if "don't support block selection at all".

***

How about the following case?

![תמונה](https://user-images.githubusercontent.com/10229320/209980067-fd719de8-aa72-42db-a465-ced232f68ca6.png)

The same selection when `Show All Characters` is OFF (_normal use_):
![תמונה](https://user-images.githubusercontent.com/10229320/209980589-681d3ebf-f54e-45cf-8c29-4b4fb13e74a4.png)

Wouldn't _excluding_ line 9 be confusing?
I think that *including* partially stream-selected lines (even if the EOL is not selected) would be clearer and more consistent.
And as you've mentioned recently: "Those commands are Line Operations".

2022-12-29 16:42 UTC, Yaron10 commented
And what should happen on `Trim both and EOL to Space`?
Include line 9 for Trim and exclude it for `EOL to Space`?

2022-12-29 20:09 UTC, donho commented
@Yaron10 

![image](https://user-images.githubusercontent.com/90293/210005391-4c3528f8-9c51-496b-9cdf-2c6c52234632.png)

For me in screen 1 the EOL of Line 4 (Test4) is selected so the Test4CRLF should be treated.
Whereas the  EOL of Line 4 in screen 2 is NOT selected, so the Test4CRLF should NOT be treated.

2022-12-30 10:23 UTC, ArkadiuszMichalski commented
@donho 

For me it's also visible and clear. When we have more control over selected EOL in the command `EOL to Space` then this command:
- can be treated more as `Join Lines` when we don't select last EOL in selection
- can be treated directly as `EOL to Space` when we select last EOL in selection

So still we have a choice, depending on what we need.

>I'm finally for don't support block selection at all (for Trim and above two commands), just return.

Hmm `Join Lines` support block selection. but if you don't want it here, we can remove it. But what should be in such a situation?

![image](https://user-images.githubusercontent.com/2730894/210059588-4b33395b-5dbe-46fa-8787-11b7f2f20548.png)

We use `Alt+Left mouse` outside the text (virtual selection). But the selection is still empty. We should return here or execute the command on the whole data (because nothing was selected)?

2022-12-30 13:36 UTC, ArkadiuszMichalski commented
OK, I removed block selection support for this commands. The code is a bit simpler. If in the future there are asking to support it, then we can think about it.

2022-12-30 13:41 UTC, donho commented
@ArkadiuszMichalski 
> Hmm `Join Lines` support block selection. but if you don't want it here, we can remove it. But what should be in such a situation?

Join Lines is a Line operation and column selection selects/includes 1 or several lines so it's not wired to users  (or to me).
Whereas "EOL to space" is NOT a Line operation, and as you said, it's different from "Join Lines", so we don't need to align the behaviour between "Join Lines" & "EOL to space".

Trim operations can be considered as a Line operation. So I think column selection could be treated on them. However, we have a command "Trim both and EOL to Space" which is combined with Trim operations (can use column selection) and "EOL to Space" (cannot use column selection).
I see 2 possible behaviours for the set of operations:
1. Trim operations treat column selection and "EOL to Space" does not treat column selection, and "Trim both and EOL to Space" does not treat column selection.
2. Trim operations, "EOL to Space" command, and "Trim both and EOL to Space" all do not treat column selection.

@ArkadiuszMichalski & @Yaron10 which solution you think more reasonable?

> We use Alt+Left mouse outside the text (virtual selection). But the selection is still empty. We should return here or execute the command on the whole data (because nothing was selected)?

It's for sure that the column selection outside of all lines shouldn't be treated. And this remind me another use case:
How about a column selection contains ONLY one long line and outside of all the other lines?
But if the behaviour 2 is chosen, then the problem above doesn't exist anymore, and the implementation will be much simpler.

2022-12-30 13:58 UTC, ArkadiuszMichalski commented
@donho 

I follow with 2 behavior, so always return when we detect column mode. This will be simpler and will not generate new borderline cases. 

I will just add that for me there was no problem with the interpretation of column mode for `EOL to Space`.
![image](https://user-images.githubusercontent.com/2730894/210077660-05199fe4-bbdf-4b16-8f8a-b962c68f7a59.png)

But now I've removed it. In practice, it's probably easier to make a normal selection than a block selection, so handling it seems unnecessary.

2022-12-30 14:10 UTC, donho requested changes
The following line should be modified:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Notepad_plus.rc#L527

2022-12-30 14:11 UTC, ArkadiuszMichalski commented
@donho 

Right, can you cancel build?

2022-12-30 15:20 UTC, donho approved these changes

2022-12-30 16:15 UTC, Yaron10 commented
> However, we have a command "Trim both and EOL to Space" which is combined with Trim operations (can use column selection) and "EOL to Space" (cannot use column selection).
I see 2 possible behaviours for the set of operations:
>
  >  Trim operations treat column selection and "EOL to Space" does not treat column selection, and "Trim both and EOL to Space" does not treat column selection.
    Trim operations, "EOL to Space" command, and "Trim both and EOL to Space" all do not treat column selection.

>> I follow with 2 behavior, so always return when we detect column mode. This will be simpler and will not generate new borderline cases.

👍 

But what about `Trim both and EOL to Space` in the following _stream selection_ case?
![תמונה](https://user-images.githubusercontent.com/10229320/210088815-09d83317-2437-40c2-9a90-c8d48b83561d.png)

I do respect and understand your approach to exclude partially selected lines in `EOL to Space`.
But I think that consistency and having less complicated rules (for @pryrt and the users reading his great documentation) are more important. :)

IMO, `EOL to Space` can certainly be interpreted as: execute the command on the selected lines (any line which have a selection).

Just some final thoughts. 
Thank you both. 👍

2022-12-30 16:27 UTC, closed without merging

2022-12-30 18:02 UTC, donho commented
@Yaron10 

Here the test (your example) with this PR by using "Trim both and EOL to Space":
![image](https://user-images.githubusercontent.com/90293/210099097-be8f74a9-0a2b-4edc-907d-39b8531e6293.png)

The result is expected (for me). What is the result you expected?

2022-12-30 18:31 UTC, Yaron10 commented
@donho,

> However, we have a command "Trim both and EOL to Space" which is combined with Trim operations (can use column selection) and "EOL to Space" (cannot use column selection).

That was a very good point. It would have been very confusing.
Let's slightly modify your comment:

However, we have a command "Trim both and EOL to Space" which is combined with Trim operations (_which **includes** partially selected lines_) and "EOL to Space" (_which **excludes** partially selected lines_).

Isn't that as confusing and unexpected as your column-selection case?

2022-12-30 18:56 UTC, donho commented
@Yaron10 
> However, we have a command "Trim both and EOL to Space" which is combined with Trim operations (_which **includes** partially selected lines_) and "EOL to Space" (_which **excludes** partially selected lines_).

> Isn't that as confusing and unexpected as your column-selection case?

Which is your suggestion then?

2022-12-30 19:06 UTC, Yaron10 commented
@donho,

I think that `EOL to Space` can be interpreted as: execute the command on the selected lines.
That is: include partially _stream-selected_ lines even if the EOL is not selected.

2022-12-31 02:11 UTC, ArkadiuszMichalski commented
Actually selection works like this:
- `EOL to Space` is not expand at all, you decide what you select.
- `Trim` is expand to full lines, but without last EOL in last line (so will not affect next command).
- `Trim both and EOL to Space` is just sequence `Trim` + `EOL to Space`. Expanding here from `Trim` doesn't affect `EOL to Space` so everything is fine. It's the same as if you manually invoked `Trim` and immediately `EOL to Space`.

If you want to include specific EOLs, just select them explicitly. I see no problem here.