Fix for Windows Notepad replacement regression (Notepad++ v8.4.8)
notepad-plus-plus/notepad-plus-plus pull request #12779
Opened 2023-01-09 01:39 UTC by xomx

Fixes #12775 .

This fixes opening of unintentional non-existing file named " " in Notepad++ v8.4.8.

The bug was there all the time, but it was invisible for users until v8.4.8 checked for such nonsense filenames.
More details in the issue.

2023-01-09 17:21 UTC, donho commented
@xomx 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12775#issuecomment-1375983014

2023-01-13 13:35 UTC, donho requested changes
When the last argument is around the quotes as the following example:
-notepadStyleCmdline -z "C:\Windows\system32\NOTEPAD.EXE" `"`C:\Users\xxxxxx\xxxxxxxx\Nouveau document texte.txt`"`
It's parsed badly in `advanceCmdLine` function and make the inconsistent output.
Therefore the bug should be fixed in `advanceCmdLine` function, but not somewhere-else.

2023-01-13 18:08 UTC, donho commented
@xomx 
FYI, I'm refactoring (for making it simpler) and after the refactoring, this bug should be fixed.

2023-01-13 21:06 UTC, xomx commented
@donho 
OK, thanks a lot, so can I close this PR?

I have to deal with something serious IRL, it looks like I won't be able to get involved here for some time.

2023-01-14 02:47 UTC, donho commented
@xomx 
> OK, thanks a lot, so can I close this PR?

Yes, go ahead.
If you have time, please check  #12800 - it should fixes the problem.

> I have to deal with something serious IRL, it looks like I won't be able to get involved here for some time.

Hope everything will go into order to you.

Thank you very much for your analyze - that helped me a lot.

2023-01-14 14:31 UTC, donho commented
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6c3659fe7300992ae7a3cd32410377bd88ac263a

2023-01-14 14:31 UTC, closed without merging

2023-01-15 18:54 UTC, xomx commented
@donho 

> If you have time, please check #12800 - it should fixes the problem.

I checked now - it is ok, good job!