Add new notification for lexer plugin
notepad-plus-plus/notepad-plus-plus pull request #13091
Opened 2023-02-10 19:00 UTC by donho

The NPPN_EXTERNALLEXERBUFFER is sent to plugins with buffer ID (idFrom) when a new lexer is applied to the buffer in question.

Fix #12351

2023-02-10 19:01 UTC, donho commented
@ blu3mania
Could you test it please?

2023-02-10 20:51 UTC, rdipardo commented
> @ blu3mania Could you test it please?

"@ blu3mania" definitely won't; but maybe @blu3mania will.

2023-02-10 21:21 UTC, ozone10 commented on PowerEditor/src/resource.h
> +	#define NPPM_INTERNAL_EXTERNALLEXERBUFFER           (NOTEPADPLUS_USER_INTERNAL + 71)
@donho 
appveyor failed
Could you rebase on latest upstream/master and change value?

2023-02-10 23:22 UTC, blu3mania requested changes

2023-02-10 23:22 UTC, blu3mania commented on PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp
> +	::SendMessage(_hParent, NPPM_INTERNAL_EXTERNALLEXERBUFFER, 0, 0);
Since NppBigSwitch is expecting lParam for this message, shouldn't it be sent?

2023-02-10 23:22 UTC, blu3mania commented on PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp
> +	::SendMessage(_hParent, NPPM_INTERNAL_EDGEMULTISETSIZE, 0, (LPARAM)getCurrentBufferID());
Not sure if you meant to send the buffer ID in NPPM_INTERNAL_EXTERNALLEXERBUFFER but accidentally changed this message instead? I don't think NppBigSwitch uses lParam for this message.

2023-02-11 01:28 UTC, donho commented
@blu3mania 
The issues you mentioned above should solved now.

2023-02-11 02:26 UTC, blu3mania commented
@donho Tested and it was working correctly. Thanks!

2023-02-11 18:21 UTC, closed without merging