Update dutch.xml
notepad-plus-plus/notepad-plus-plus pull request #13148
Opened 2023-02-16 14:46 UTC by RockyTDR

2023-02-16 15:42 UTC, ArkadiuszMichalski commented
@RockyTDR You can't nest quotes `""` inside quotes `""` (use `&quot;` instead or other entity).
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f0095d24d2c25a65da8aed71739ea26e21e5b22a/PowerEditor/installer/nativeLang/dutch.xml#L1673

2023-02-16 23:53 UTC, donho requested changes
Fix the xml validation error.

2023-02-21 00:27 UTC, donho approved these changes

2023-02-24 01:27 UTC, donho commented
Could you please check the following announcement for completing your localization file if it's not done?
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13209

Thank you @RockyTDR

2023-02-26 20:06 UTC, closed without merging