update korean translate (8.5.1)
notepad-plus-plus/notepad-plus-plus pull request #13400
Opened 2023-03-24 08:24 UTC by yunbj

2023-03-24 15:13 UTC, ILIKECHICKENTOOMUCH commented
@yunbj  
안녕하세요. 한글 업데이트를 기다리고 있었어요. 감사합니다.
추가로 한가지 여쭐게 있는데요. 
한글 업데이트를 해주신 8.5.1 버전을 다운로드하여도 "새로운 1", "새로운 2"와 같은 탭 제목에서 
우클릭 하면 나타나는 메뉴는 영어로 표시되더라고요. 이번에 업데이트가 이루어진 부분은 이것과 무관한 부분인가요?

2023-03-27 01:30 UTC, yunbj commented
@ILIKECHICKENTOOMUCH 

안녕하세요. 제가 작업하는 방식은 마지막 작업했던 english.xml 파일의 변경 사항을 확인하고 변경 사항 부분에 대해 업데이트를 하고 있습니다.
우클릭하면 나타나는 메뉴에 영어로 표시되고 있다면 아직 메뉴를 리소스로 분리하지 않아서 그런 것이 아닐까 합니다.

2023-04-02 01:07 UTC, donho requested changes
Please replace all `CMID` by `CMDID`

2023-04-02 01:07 UTC, donho commented on PowerEditor/installer/nativeLang/korean.xml
> +  <Item CMID="41003" name="닫기"/>
should be `CMDID` instead of `CMID`

2023-04-03 23:06 UTC, donho approved these changes

2023-04-04 13:22 UTC, closed without merging