[xml] Update Corsican translation for Notepad++ 8.5.6
notepad-plus-plus/notepad-plus-plus pull request #13978
Opened 2023-08-06 15:03 UTC by Patriccollu

Hello,

This is an update of **Corsican** localization to take into account the following commits:

 * https://github.com/notepad-plus-plus/notepad-plus-plus/commit/391f4281efac81649a02aa8cdd4e765fa76d1237 Fix leading & tailling spaces being allowed after renaming tab issue

Cheers,
Patriccollu.

2023-08-07 16:19 UTC, donho requested changes
correct version number

2023-08-07 16:19 UTC, donho commented on PowerEditor/installer/nativeLang/corsican.xml
> +	<Native-Langue name="Corsu" filename="corsican.xml" version="8.5.6">
it'll always be v8.5.5

2023-08-07 16:40 UTC, Patriccollu commented
Hello @donho 

I'm sorry! As I noticed an announcement for v8.5.5 RC, I thought there was no changes for translation any more.

I just modified the version number, as you requested.

Cheers,
Patriccollu.

2023-08-09 21:51 UTC, Patriccollu commented
Notepad++ 8.5.5 has just been released which means this PR will be taken into account for next release.

2023-08-14 16:36 UTC, donho approved these changes

2023-08-14 16:42 UTC, closed without merging