Greatly speed up reloading document list.
notepad-plus-plus/notepad-plus-plus pull request #14080
Opened 2023-09-01 01:22 UTC by Orden4

Addresses https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13479 and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12632
Simply supplies an additional argument to `VerticalFileSwitcherListView::remove` so that it doesn't delete the item, allowing you to do it in bulk later, which greatly reduces the number of redraws required.

This reduces the time it takes to drag a tab from first to last/last to first with 138 files opened from ~1m55s to ~20s. Still a considerable time, but at least it's no longer increasing exponentially with number of files opened (see https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13479#issuecomment-1682160614 for a more detailed explanation).

A more ideal solution would likely be to actively swap items instead of reloading everything, but I'm too inexperienced in C++ to really get anywhere on that, so I just did the best I can to address a thing that's been driving me mad for months to at least a bearable level.

2023-09-04 15:50 UTC, donho requested changes
Please change del to removeFromListview.

2023-09-04 15:50 UTC, donho commented on PowerEditor/src/WinControls/VerticalFileSwitcher/VerticalFileSwitcherListView.h
> +	void remove(int index, bool del = true);
Please change **del** to **removeFromListview**.

2023-09-04 16:25 UTC, donho commented
BTW, I notice that you're using master to create your PR. It's OK for this time, but please create a new branch for every new PR.
Ref:  https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests

2023-09-05 14:45 UTC, closed without merging

2023-09-06 06:18 UTC, Orden4 commented
Sorry, am horrible at checking personal e-mail during workdays. Thanks for including the PR anyway!

2023-09-12 21:53 UTC, SlugFiller commented
This is only half the solution. Adding the items would still be slow. The correct way to handle bulk updates is with `WM_SETREDRAW`. You set it to `FALSE` at the start of the bulk update, set it to `TRUE` at the end, and then call `RedrawWindow` on the control to update everything at once. This should reduce it from 20s to under a second.

2023-09-13 00:51 UTC, Orden4 commented
> This is only half the solution. Adding the items would still be slow. The correct way to handle bulk updates is with `WM_SETREDRAW`. You set it to `FALSE` at the start of the bulk update, set it to `TRUE` at the end, and then call `RedrawWindow` on the control to update everything at once. This should reduce it from 20s to under a second.

Ah, so that's is how you're meant to do that. I did try to find such a thing but google just wasn't any help.

Anyway, just for clarity let me first say that 20s is the time for moving it across 138 items 1 by 1 (by holding the file at the far left or right of the tab list), you don't really *want* it to move 138 items across in less than a second because that'd just be uncontrollable. Anyway, by adding `WM_SETREDRAW` around the first two lines of the reload method like this:
```cpp
	::SendMessage(_hParent, WM_SETREDRAW, false, 0);
	removeAll();
	initList();
	::SendMessage(_hParent, WM_SETREDRAW, true, 0);
```
It moves at something like 15 to 20 items per second regardless of list size, which is significantly faster but still just slow enough to follow, so that seems like a good balance to me.
However, the one oddity is that the selection will always be off by one during the dragging process, and I can't really seem to get that to draw properly.

2023-09-13 08:09 UTC, SlugFiller commented
I'm fairly sure that should be `_hSelf` not `_hParent`. ListView has special handling for `WM_SETREDRAW` which disables all sort of actions it performs during item add, like sorting, updating user data, etc. That's why it's important to send it to the ListView itself.

There's also a macro for it it's `SetWindowRedraw`. So that could be `SetWindowRedraw(_hSelf, FALSE);`

For the draw delay, are you calling `RedrawWindow` on the list after re-enabling drawing? If you want to be extra fast, you can pass the flag `RDW_UPDATENOW`, although even without it, redraw should happen within a frame. Another possibility is to call `ListView_RedrawItems` to inform it that it needs to update. That should be called after enabling drawing, and before calling `RedrawWindow`. And, again, the redraw should be on `_hSelf`, not `_hParent`

2023-09-13 10:22 UTC, Orden4 commented
It's probably best to comment on the new PR that I made rather than this old PR, but anyway.

Suppressing redraw on `_hSelf` instead of `_hParent` will cause the list to rapidly flicker while moving items down. I guess it may be useful to suppress both or something just to make it slightly more performant. But at least on my own PC there's no meaningful performance gain anymore anyway, as I'd say having it move faster than 15~20 items per second will just make it difficult to control.

Furthermore, regarding the redrawing stuff, the biggest reason from what I could tell was just that the order isn't actually updated prior to calling `reload`. Later on there is a call to `activateItem` at which it *is* actually updated properly, so I just made it made it do an explicit repaint only at the end of that which gave an excellent end result that works fast and doesn't flicker.