Fix possible missing 'SessionFileInvalidError' message in MultiInst configs
notepad-plus-plus/notepad-plus-plus pull request #14232
Opened 2023-10-14 02:29 UTC by xomx

Fix #14228 

Moving the error-dlg to the `NppParameters::loadSession` is more universal.

Other minor improvements (in `Notepad_plus::fileLoadSession`):
- checking also for a possible ShellExecute error
- removing the `isAllSuccessful` boolean, as it is no longer needed (due to previous patch by @donho )

2023-10-14 13:05 UTC, Yaron10 commented
@xomx,

👍 
Thank you for the nice fix and the fine-turning.

2023-10-14 14:28 UTC, donho commented
@xomx 
Thank you for the fix.
It was assigned to me for not forgetting to check it. However, I'm not sure that #14228 is a valid bug to me.
I will check it ASAP.

2023-10-16 19:37 UTC, Yaron10 commented
> Thank you for the nice fix

The "Thank you" is valid and reinforced. :)
As for the fix: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14228#issuecomment-1763141359.
Removing the message altogether might be an option. - You don't prompt if session.xml or other XML files are corrupted.

2023-10-17 01:13 UTC, donho commented
@Yaron10 
> Removing the message altogether might be an option. - You don't prompt if session.xml or other XML files are corrupted.

Sorry if I misunderstand you (again), but I'm confused: Does the issue you created #14228 **"Session file is corrupted" message may not be displayed** ask to display a message if XML is corrupted?

2023-10-17 01:22 UTC, donho commented
@Yaron10 


OK, I see. you mean that in the case of plugin message NPPM_GETNBSESSIONFILES & NPPM_GETSESSIONFILES, the message box should not be displayed - that's a good point, and I agree with you.

2023-10-17 13:20 UTC, Yaron10 commented
@donho,

The issue was evolving. :)

1. I did not (and still don't) suggest to display a message if any XML file used by NPP was corrupted.
2. As we all agree the message should not be displayed in `NPPM_GETNBSESSIONFILES` & `NPPM_GETSESSIONFILES`,
we have two options: modifying `nppParam.loadSession()`, or removing the message altogether.
As long as NPP do not prompt on corrupted session.xml (and others), I don't understand why corrupted user-session should be different (so IMO Removing the message altogether would be better).

2023-10-18 12:51 UTC, donho commented
@Yaron10 
> I did not (and still don't) suggest to display a message if any XML file used by NPP was corrupted.

So what the issue #14228 about is to remove the message box but not to display it?

> As long as NPP does not prompt on corrupted session.xml (and others), I don't understand why corrupted user-session should be different (so IMO removing the message altogether would be better).

The session.xml file is managed by the application - Notepad++ loads and saves it automatically, so users have no control over it. In contrast, user-created sessions are entirely in the hands of the users - they load and save them manually, and Notepad++ does not modify them. From this viewpoint, invalid session.xml files can be ignored by Notepad++ for the sake of user experience.

Speaking of user experience, session.xml files are loaded on startup of Notepad++. Therefore, the message box that appears on startup can break the user experience. On the other hand, user-created sessions are loaded manually by users who know what they are doing, so an error message box does not bother them.

Of course, my sense follows both user experience and consistency of tool. But when there’s a conflict between them, then for me the user experience should be the priority.

2023-10-18 13:56 UTC, Yaron10 commented
@donho,

> So what the issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14228 about is to remove the message box but not to display it?

As I wrote earlier: the issue & solution were evolving.

> The session.xml file is managed by the application - Notepad++ loads and saves it automatically, so users have no control over it. In contrast...

When I started reading that paragraph, I thought your argument would be: NPP should over-write and "re-valid" session.xml on exit.

Anyway, I understand you prefer to keep the message.
So be it. :)

2023-10-18 14:34 UTC, donho requested changes
Please 
1. solve the conflict
2. Remove the message from the 2 plugin messages
3. implement as following specs: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14228#issuecomment-1767258536

2023-10-21 01:27 UTC, donho requested changes
Please change the variable name for following the convention in this block (ie. "sessionFileName", but not "pIn") and improving the readability of code.

2023-10-21 01:27 UTC, donho commented on PowerEditor/src/NppBigSwitch.cpp
> +			BOOL* pbOut = reinterpret_cast<BOOL*>(wParam);
Please use isValidXML instead of pOut for being more explicit.
```cpp
BOOL* isValidXML = reinterpret_cast<BOOL*>(wParam);
```

2023-10-21 19:27 UTC, xomx commented
@donho 
Sorry (now I re-read your comment) - did you really mean using `isValidXML` (instead of the current `pbIsValidXML`) for a pointer?

2023-10-21 22:58 UTC, donho commented
> @donho Sorry (now I re-read your comment) - did you really mean using `isValidXML` (instead of the current `pbIsValidXML`) for a pointer?

@xomx 
It's OK `pbIsValidXML` though it's not my coding style.
The most important is to make it meaningful so 10 years later when the maintainer checks the code he/she can understand what is the code doing without checking Notepad++ user-manual.

2023-10-21 22:59 UTC, donho approved these changes

2023-10-22 23:11 UTC, closed without merging