Fix issue 5217
notepad-plus-plus/notepad-plus-plus pull request #14613
Opened 2024-01-17 17:52 UTC by anatoly77g

When recording a keyboard macro, some commands are added to the macro twice. When later playing back the macro, they happen twice, which leads to incorrect edits.

Fixed commands:
EDIT_CUT (Cut)
IDM_EDIT_INS_TAB (Increase Line Indent)
IDM_EDIT_RMV_TAB (Decrease Line Indent)
IDM_EDIT_LINE_UP (Move Up Current Line)
IDM_EDIT_LINE_DOWN (Move Down Current Line)

Not fixed: issue 13722:
SEARCH_GOTOMATCHINGBRACE (Go to Matching Brace)

2024-01-30 17:53 UTC, MarkusBodensee commented
See also issue #14634

2024-02-03 17:45 UTC, donho commented
@anatoly77g 
The following commands are removed from recording in your PR: 
IDM_EDIT_INS_TAB (Increase Line Indent)
IDM_EDIT_RMV_TAB (Decrease Line Indent)

Could you provide the way for reproduce the duplication please?

2024-02-03 17:58 UTC, donho requested changes
Remove IDM_EDIT_COPY please.

2024-02-03 17:58 UTC, donho commented on PowerEditor/src/NppCommands.cpp
>  			case IDM_EDIT_COPY:
IDM_EDIT_COPY can also be removed

2024-02-04 10:11 UTC, anatoly77g commented
> @anatoly77g The following commands are removed from recording in your PR: IDM_EDIT_INS_TAB (Increase Line Indent) IDM_EDIT_RMV_TAB (Decrease Line Indent)
> 
> Could you provide the way for reproduce the duplication please?

Start with an empty buffer.
1. Press 'a' and Enter.
2. Press Shift + Up to select the line with 'a' in it.
3. Press Ctrl + Shift + R to start recording a macro.
4. Choose from the menu: Edit - Indent - Increase Line Indent.
5. Press Ctrl + Shift + R to stop the recording.
6. Press Ctrl + Shift + P to play the recorded macro.
7. The line is indented twice.

I now see that my change doesn't fix this "Increase Line Indent" properly — it spoils the macro recording in other scenarios involving indentation. Probably worth making a separate issue for this; please confirm!
Meanwhile, I remove all changes related to indentation.

2024-02-04 10:45 UTC, anatoly77g reviewed
Finished my review

2024-02-04 11:43 UTC, donho commented on PowerEditor/src/NppCommands.cpp
> +			case IDM_EDIT_RMV_TAB:
OK I can reproduce the duplication.
But why IDM_EDIT_INS_TAB & IDM_EDIT_RMV_TAB can be removed but not always?

2024-02-04 13:08 UTC, anatoly77g commented
I believe commenting-out is a poor programming practice, so I prefer doing it more explicitly.
I suggest creating a dedicated do-nothing case in the switch statement, with comments which explain what's going on, and move all related commands to it.
Not sure this is acceptable as I am not familiar with pull-request rules in this project.
Please express your opinion.

2024-02-04 14:07 UTC, donho commented
> I suggest creating a dedicated do-nothing case in the switch statement, with comments which explain what's going on, and move all related commands to it.

It's a better idea indeed. OK let's do it this way.

2024-02-04 14:20 UTC, donho approved these changes

2024-02-04 14:30 UTC, anatoly77g commented
Behavior of "increase/decrease indentation" commands depends on what is selected. At certain conditions "depart from Scintilla behavior and do it our way", as some comment mentions. So correct recording of indentation commands in a macro requires some logic — sometimes, record the menu-command, other times record the Scintilla-command.
I guess several other commands have this problem; it may require some systematic approach.

2024-02-04 14:34 UTC, donho commented
@anatoly77g 
Thank you for the explanation!

2024-02-04 14:41 UTC, closed without merging

2025-08-31 07:31 UTC, victorel-petrovich commented
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14613#issuecomment-1925676045
> I now see that my change doesn't fix this "Increase Line Indent" properly — it spoils the macro recording in other scenarios involving indentation. Probably worth making a separate issue for this; please confirm!

Here is the issue, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/16960 ,  together with a case where removing the menu actions from recording would not work.