Update polish.xml
notepad-plus-plus/notepad-plus-plus pull request #14792
Opened 2024-02-26 09:35 UTC by piotrtrkostrzewski94

Adaptation for commit 12548b6

2024-02-26 13:07 UTC, piotrtrkostrzewski94 commented on PowerEditor/installer/nativeLang/polish.xml
> +			        </Scintillas>
I implemented your suggestion. Thank you for info.

2024-02-26 15:57 UTC, donho requested changes
Please move the indicated entries from Scintillas tag to Scintillas2 tag.

2024-03-10 08:47 UTC, piotrtrkostrzewski94 commented
@donho I made the change you requested and I still get the information that Changes requested, could you check my changes?  Have a nice day.

2024-03-10 20:49 UTC, donho approved these changes

2024-03-10 21:26 UTC, piotrtrkostrzewski94 commented
Thank you very much. Have a nice week.

2024-03-15 00:00 UTC, closed without merging