Improve hiDPI appearance for some DM elements
notepad-plus-plus/notepad-plus-plus pull request #14818
Opened 2024-03-01 17:41 UTC by ozone10

fix #14817

2024-03-02 18:05 UTC, chcg commented
@ozone10 Does this change the supported win versions? See https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/SUPPORTED_SYSTEM.md .

2024-03-02 19:05 UTC, ozone10 commented
@chcg 
no.
`_WIN32_WINNT=_WIN32_WINNT_WIN10 NTDDI_VERSION=NTDDI_WIN10_RS5` are needed for Windows 10 DPI APIs.
Before calling them we check that OS is supported with if clause `NppDarkMode::isWindows10()`, so there should be no issue with it.

It's possible to not use them, but it would require using undocumented APIs.

This PR is also preparation to properly support HiDPI for Windows 10/11 and newer.

2024-03-03 00:14 UTC, xomx commented
@ozone10 
> This PR is also preparation to properly support HiDPI for Windows 10/11 and newer.

When I saw the details of this PR, I was hoping you would say something like this.
So can we look forward to PerMonitor DPI-Aware stuff etc?

2024-03-08 21:31 UTC, ozone10 commented
@xomx 
I will try to prepare and implement basic stuffs. But some elements will require more, e.g. Window dlg, docking panels tab and for some of them their contents, support for plugins, ...

2024-03-11 22:24 UTC, donho commented
> This PR is also preparation to properly support HiDPI for Windows 10/11 and newer.

>>When I saw the details of this PR, I was hoping you would say something like this.
>>So can we look forward to PerMonitor DPI-Aware stuff etc?

>>>I will try to prepare and implement basic stuffs. But some elements will require more, e.g. Window dlg, docking panels tab and for some of them their contents, support for plugins, ...

@ozone10 
If I understand well, DPIManagerV2, which will manage better in Win11 and next version of Windows, can replace current DPI Manager in the future?

2024-03-11 22:49 UTC, donho requested changes
Please follow the suggestions:

2024-03-12 07:06 UTC, ozone10 commented on PowerEditor/src/dpiAware.manifest
> +            <dpiAwareness>system, unaware</dpiAwareness>
`unaware` parameter is never used, on older Windows `dpiAwareness` is ignored and `dpiAware` is used, on newer `dpiAwareness` with "Per Monitor" parameters (if supported by OS) has higher priority.
 I included it mainly for hint how to add `PerMonitorV2` parameter in future 
```
<dpiAwareness>PerMonitorV2, system, unaware</dpiAwareness>
```
[ref](https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process)

2024-03-12 07:11 UTC, ozone10 commented
> If I do understand well, DPIManagerV2, which will manage better in Win11 and next version of Windows, can replace current DPI Manager in the future?

Yes, currently the old DPI Manager only support system aware context – it has same global dpi scale value for all windows/dialogs/controls/elements. But windows can have different dpi scale (e.g. find&replace dlg on second monitor) .

2024-03-12 17:01 UTC, donho approved these changes

2024-03-12 17:04 UTC, closed without merging

2024-03-13 04:33 UTC, astewart77 commented
So is this the end of using n++ on Windows 7?

`The procedure entry point GetDpiForWindow could not be located in the dynamic link library USER32.dll. `