Ada Function List improvements
notepad-plus-plus/notepad-plus-plus pull request #14986
Opened 2024-04-12 19:24 UTC by notdodgeball

Fix #14908 #14687 #14498

Changes:
Ada is case insensitive
Added 'Parallel' reserved word
Identifiers may not begin or end with underscore
Support for identifiers containing digits
Support for Ada specifications file (subprogram declaration) (#14687)
Support for dot notation within types (#14908)
Support for generic instantiations (#14498) (functions with no return statement)

2024-04-12 20:01 UTC, MAPJe71 requested changes
Could you add a link to the ADA version or simply/just the ADA version this complies to?

2024-04-12 20:37 UTC, notdodgeball commented on PowerEditor/installer/functionList/ada.xml
> -							(?:(?&amp;PARAMETERS))?                         # Boost::Regex 1.58-1.59 do not correctly handle quantifiers on subroutine calls
I couldn't find a mention of it being fixed in the [changelog](https://www.boost.org/doc/libs/1_84_0/libs/regex/doc/html/boost_regex/background/history.html)

But from the tests I've done, it no longer applies, therefore I removed it and simplified the expression.

2024-04-13 03:51 UTC, rdipardo commented
This PR should include updated [unit tests](https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/Test/FunctionList/ada):

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/e0bb723700c2ed75da90284bcf0e33300e3463ff/CONTRIBUTING.md?plain=1#L33

2024-04-14 12:44 UTC, donho requested changes
(Repeat @rdipardo has said)
This PR should include updated [unit tests](https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/Test/FunctionList/ada):

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/e0bb723700c2ed75da90284bcf0e33300e3463ff/CONTRIBUTING.md?plain=1#L33

2024-04-14 17:13 UTC, chcg commented
Changes which might be tested via extended unittest file:
https://learn.adacore.com/courses/whats-new-in-ada-2022/chapters/introduction.html

2024-04-19 04:22 UTC, ronww commented
I tested this change and it appears to work for my current project.

2024-04-22 15:13 UTC, donho commented
@ronww 
Could you provide the ADA samples here, regarding the 3 bug reports you've done, which didn't work, but work now with this PR?

2024-04-22 16:30 UTC, ronww commented
I spoke too soon. Some specifications (aka "prototypes") are still not listed:
![NP++FuncList](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/62124/c26f3375-e69b-4fe4-a285-b2223e8b548a)

2024-04-22 16:41 UTC, ronww commented
Examples:
![NP++FuncList](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/62124/ae058205-1a67-4138-8488-a72fb356c288)


function Int32toInt8TwosComplement (value : Vt.Int32) return Vt.Int8 is
begin
    -- body
end Int32toInt8TwosComplement;

2024-04-26 18:08 UTC, ronww commented
Just discovered that functions/procedure specifications and definitions with comments in the parameter list fail to show in the Function List

Example:
procedure Test_Get_Register(
Reg : Address_Range; -- Register to test
Page : Page_Range; -- Page of target register
ID : String; -- Test case identification
) is
begin
-- code
end Test_Get_Register;

If the comments in the parameter list are removed, then the procedure is shown.

2024-04-26 18:11 UTC, MAPJe71 commented
see https://community.notepad-plus-plus.org/topic/19480/faq-function-list-basics

2024-05-02 00:28 UTC, donho commented
@ronww 
I need only some ADA samples here (no comment, no explanation), regarding the current fixed, which didn't work, but work now with this PR?
Without these samples I cannot integrate this fix.

2024-05-04 18:39 UTC, ronww commented
All of these should work, but some still do not work


function Get_Idle
return Boolean;

function Get_Phase
-- Purpose: Returns current phase
return Integer;

function Get_State
return Vt.State;

procedure Update;

function Int32_To_Byte_Array is
new Unchecked_Conversion (Source => Vt.Int32, Target => Vt.Byte_Array);

function Int8_To_U8 is new Unchecked_Conversion
(Source => Vt.Int8, Target => Vt.U8);

function Int32toInt8TwosComplement (value : Vt.Int32) return Vt.Int8 is
begin
-- body
end Int32toInt8TwosComplement;

function AproxU8 (n : Vt.U8; x : Vt.U8) return Boolean is
eq : Boolean := False;
begin
-- code
return eq;
end AproxU8;

function Read_I32 (Register : Vt.Address_Range) return Vt.Int_32 is
Data : Vt.Int_32;
begin
-- code
return Data;
end Read_ I32;

procedure Test_Get_Register(
Reg : Address_Range; -- Register to test
Page : Page_Range; -- Page of target register
ID : String; -- Test case identification
) is
begin
-- code
end Test_Get_Register;

2024-05-05 20:17 UTC, donho commented
@ronww 
Thank you!

2024-05-05 20:21 UTC, closed without merging