Update french.xml
notepad-plus-plus/notepad-plus-plus pull request #15355
Opened 2024-06-25 00:15 UTC by Need74

Good morning
I have just completely restarted the translation of Notepad++ into fr Essentially there are many deletions of capital letters in the middle of sentences (non-compliant in French) Replacing the apostrophes ' with ' (alt+0146) (to make it prettier) Replacement of "" (&quot;) by French quotation marks "" (alt+174 & alt175)(to make it prettier too) Some formulations which were not very clear, or even incorrect. I'm still tweaking a few things but that will be for a future PR Sincerely
Dennis

2024-06-25 00:25 UTC, Need74 commented
If you want to quickly see the effect of the differences I am attaching the Tatar file. xml
You just have to copy it into the Notepad++-backslash-Localization folder and then choose to change the Tatar language (I hope it's not yours)
Sincerely
Dennis
[tatar.xml.patch](https://github.com/user-attachments/files/15962741/tatar.xml.patch)
You must rename tatar.xml.patch in tatar.xml before copying

2024-06-26 15:31 UTC, donho requested changes
Looks great! Please follow the suggestions below:

2024-06-26 15:31 UTC, donho commented on PowerEditor/installer/nativeLang/french.xml
> +					<Item id="6303" name="Taille : "/><!-- Espace réduit -->
In the latest release (v8.6.8), this entry is enlarged.

2024-06-26 22:00 UTC, Need74 commented on PowerEditor/installer/nativeLang/french.xml
> +					<Item id="43053" name="Sélectionner tout entre les 2 accolades {}"/>
So it is better not to talk about "braces" and only put " { } or [ ] or ( ) "
The note is also useful for the English "braces text" and I can put a PR for that.
"Select All Between &amp;Matching Braces" Will be "Select All Between &amp;Matching  { } or [ ] or ( )"

2024-06-26 22:07 UTC, Need74 commented on PowerEditor/installer/nativeLang/french.xml
> +					<Item id="46016" name="Aucun (Texte normal)"/>
Thank you
The note is also useful for the English "None (Normal Text)" and I can put in the same PR for that.

2024-06-26 23:31 UTC, Need74 reviewed
Just an error " ? "

2024-06-27 13:18 UTC, donho commented on PowerEditor/installer/nativeLang/french.xml
> +					<Item id="43053" name="Sélectionner tout entre les 2 accolades {}"/>
@Need74 
OK for French to contain "{ } or [ ] or ( )".
For English, I will take care of it myself.

2024-06-27 13:22 UTC, donho requested changes
For the PR being accepted, please 
1. remove the modification of english.xml from this PR.
2. Follow the given suggestions about french.xml

2024-06-27 21:47 UTC, Need74 commented
> For the PR being accepted, please
> 
>     1. remove the modification of english.xml from this PR.
> 
>     2. follow the given suggestions about french.xml

Thank you for taking the time to read and understand the meaning of my PR.
It seems obvious to me that modifying the "English language master" file on which all translations depend must be done with the greatest care.
I don't know if you understood it, but the multiple line breaks I made were intended to make it easier to read the file in text mode and to better identify the beginnings and ends of main sections.
At this time I can no longer intervene on the modification of the english.xml file since the PR is closed and therefore do not understand what you expect from me.
For the PR in progress on french.xml I continue to follow it while waiting for its approval.
I remain at your disposal for any further information and thank you for your involvement in the world of free software.
Sincerely
Dennis

2024-06-28 13:04 UTC, Need74 commented
> > At this time I can no longer intervene on the modification of the english.xml file since the PR is closed and therefore do not understand what you expect from me.
> 
> You modified english.xml in this PR, too. Look at the Files changed tab.

I hope I did the right thing, it now says: "this commit does not contain any modifications" "the file is deleted"

2024-06-28 13:12 UTC, donho commented
@Need74 
No, the action you have done is deleting english.xml. What you should do is restore english.xml as it was.

2024-06-28 14:14 UTC, Need74 reviewed
I have reset all

2024-06-28 14:52 UTC, Need74 commented
> @Need74 No, the action you have done is deleting english.xml. What you should do is restore english.xml as it was.

What should I do to restore the english.xml file to its original state?
When I try to edit the file to restore it, the system tells me that the file does not exist.
I specify that I work exclusively with the github graphical interface because I have never used the command lines.
I will need a point by point explanation to get there.
In any case I can also close my PR and create a new one with only the accepted modifications of my french.xml file.
thank you for your reply

2024-06-28 15:16 UTC, Need74 reviewed
After restor

2024-06-29 16:19 UTC, donho requested changes
1. Modify`<Item id="43053" name="Sélectionner tout entre les 2 accolades {}"/>` to `<Item id="43053" name="Sélectionner tout entre les 2 accolades {} [] ou ()"/>`
2. Modify `<Item CMDID="10003" name="Déplacer vers une nouvelle instance (fenêtre)"/>` to `<Item CMDID="10003" name="Déplacer vers une nouvelle instance"/>`
3. Modify `<Item CMDID="10004" name="Ouvrir dans une nouvelle instance (fenêtre)"/>` to `<Item CMDID="10004" name="Ouvrir dans une nouvelle instance"/>`
4. Restore `<Item id="1632" name="Dans la sélection"/>`
5. Restore `<Item id="20012" name="Ignorer la casse"/>`
6. Restore `<Item id="6303" name="Taille de l'indentation :"/>`

2024-06-29 22:34 UTC, Need74 commented
> 1. Modify`<Item id="43053" name="Sélectionner tout entre les 2 accolades {}"/>` to `<Item id="43053" name="Sélectionner tout entre les 2 accolades {} [] ou ()"/>`
> 
>     2. Modify `<Item CMDID="10003" name="Déplacer vers une nouvelle instance (fenêtre)"/>` to `<Item CMDID="10003" name="Déplacer vers une nouvelle instance"/>`
> 
>     3. Modify `<Item CMDID="10004" name="Ouvrir dans une nouvelle instance (fenêtre)"/>` to `<Item CMDID="10004" name="Ouvrir dans une nouvelle instance"/>`
> 
>     4. Restore `<Item id="1632" name="Dans la sélection"/>`
> 
>     5. Restore `<Item id="20012" name="Ignorer la casse"/>`
> 
>     6. Restore `<Item id="6303" name="Taille de l'indentation :"/>`

I hope I have done what is necessary, I still have some improvements to make but this will be the subject of a future PR, when I have fully mastered the new version.
Sincerely

Dennis

2024-06-29 23:28 UTC, donho approved these changes

2024-06-29 23:35 UTC, closed without merging