Replace treeview bmp with ico
notepad-plus-plus/notepad-plus-plus pull request #15405
Opened 2024-07-05 14:00 UTC by ozone10

- use recommended subclassing
- fix missing icons in function list when searching

ref #14959

2024-07-16 22:22 UTC, donho requested changes
~~Remove SetWindowSubclass call for not modifying the retured value and keep the legacy windows subclass way.~~

2024-07-19 16:48 UTC, ozone10 commented
rebased to fix conflict with master

2024-07-19 16:57 UTC, donho commented on PowerEditor/src/NppBigSwitch.cpp
> +			_mainDocTab.setCloseBtnImageList();
👍

2024-07-19 17:00 UTC, donho commented on PowerEditor/src/WinControls/TreeView/TreeView.h
> +	bool setImageList(std::vector<int> imageIds, int imgSize = 0);
👍

2024-07-19 17:10 UTC, donho commented
> rebased to fix conflict with master

No worry, I'm doing it locally.

2024-07-19 17:21 UTC, closed without merging