Implement means for SaveACopyAs to open the copy post-save
notepad-plus-plus/notepad-plus-plus pull request #15476
Opened 2024-07-25 11:51 UTC by alankilborn

Fix #11861

2024-07-25 15:35 UTC, MarkusBodensee commented
And futher comments there in PR #15413

2024-07-25 16:16 UTC, donho requested changes
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15413#discussion_r1678674104

2024-07-25 16:16 UTC, donho commented on PowerEditor/src/WinControls/OpenSaveFileDialog/CustomFileDialog.cpp
> +	bool _isOpeningTheCopy = false;
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15413#discussion_r1678674104

2024-07-25 16:39 UTC, alankilborn commented on PowerEditor/src/WinControls/OpenSaveFileDialog/CustomFileDialog.cpp
> +	bool _isOpeningTheCopy = false;
Oops, missed deletion.  :-(

2024-07-25 16:54 UTC, alankilborn commented on PowerEditor/src/WinControls/OpenSaveFileDialog/CustomFileDialog.cpp
> +	bool _isOpeningTheCopy = false;
Hmm, something bigger went wrong.  :-(

2024-07-26 10:20 UTC, donho approved these changes

2024-07-26 10:32 UTC, closed without merging