Add new SubStyles and their available keyword lists
notepad-plus-plus/notepad-plus-plus pull request #15537
Opened 2024-08-11 22:43 UTC by pryrt

- Enable 8 Scintilla's SubStyles (each), which allow for new keyword lists and styles for the languages with SubStyles available: ActionScript, ASP, Bash, C, C++, C#, GDScript, Go, HTML, Java, JavaScript (standalone and embedded), JSP, Lua, PHP, Python, Resource (RC), Swift, TypeScript, and XML.
- The new SubStyles have been added to `langs.model.xml`, `stylers.model.xml`, and the themes, which means users can just use the StyleConfigurator for the SubStyles, just like they do for the original Styles.

Fixes #15520

2024-08-12 19:14 UTC, pryrt commented
@alankilborn messaged me -- he thought it was confusing that Styles that have an empty list in `langs.xml` would still show the empty **Default keywords** box:
![image](https://github.com/user-attachments/assets/4b26b439-ea3a-4e3a-bc94-beb9a7c74f77)

His suggestion was to hide that box, because users would only be expecting to see the **User-defined keywords** box for these new lists.

I would have no clue how to hide that box "on the fly", but he said he'd try to look into it and figure it out.  In the meantime, he asked me to mark this as "work in progress" rather than "ready for review"

@donho ,

Which of these would you prefer?

1. The current implementation, where **Default keywords** shows up even when empty.  (If so, please let us know, so that Alan can avoid wasting his time digging into it, and I can convert it back to "ready for review".)
2. On the SubStyle-based entries, hide the **Default keywords** entries if `langs.xml` doesn't define default keywords for it.  (But for ones like PHP, where I used some of the substyle# entries for splitting up the 9000-keyword `instre1`, or if any user edits their own `langs.xml`, still show the **Default keywords** if they _do_ populate the "default" values.)
3. On _any_ styler entry, hide the **Default keywords** list if the `langs.xml` doesn't have a value.
4. Something else that I haven't thought of.

2024-08-13 01:36 UTC, donho commented
@pryrt 
In you opinion, should people have any way to add Default keywords manually in langs.xml?

2024-08-13 02:11 UTC, pryrt commented
@donho , my vote would be for "yes". 

I actually used it to help clean up the PHP keywords (which had > 9000 all in the `instre1`) into separate categories in the langs.xml that I submitted.  

I think we would eventually regret treating it differently to a "normal" keyword list, when the user won't see the technical difference, and the Lexilla team treats it as the official way to get additional keyword lists.  (It would enable, for example, allowing an IT department to distribute their own lands.xml with company-common keywords for a given language.  And give us room, in the future, to rename use one of the substyle entries to distribute additional keywords separately from the already-used keyword slots)

2024-08-13 13:42 UTC, donho commented
@pryrt 
> my vote would be for "yes".
I actually used it to help clean up the PHP keywords (which had > 9000 all in the instre1) into separate categories in the langs.xml that I submitted.

For which reason the PHP keywords are needed to separated?

BTW
I've tried PR, and the result of **USER KEYWORDS 1**'s Default keywords in PHP is empty:

![image](https://github.com/user-attachments/assets/ca87fadd-e852-4625-b536-e9c463e097b3)

The path of langs.xml is `%APPDATA%\notepad++\langs.xml`.
Is it normal?
> I think we would eventually regret treating it differently to a "normal" keyword list, when the user won't see the technical difference, and the Lexilla team treats it as the official way to get additional keyword lists....

Sorry, I don't follow you. Could you elaborate it please?

2024-08-13 15:33 UTC, pryrt commented
> @pryrt
> For which reason the PHP keywords are needed to separated?

The original [forum question](https://community.notepad-plus-plus.org/topic/25980/highlighting-with-self-created-words-in-langs-xml-does-not-work) which prompted my finding out that SubStyles exist and learning how to implement them was because users want to be able to use a different color for the language constructs (`if`, `for`, etc) compared to the default-library functions-and-methods (`imagecreatefrombmp`, `sin`, `bin2hex`, ... and thousands more)

> BTW I've tried PR, and the result of **USER KEYWORDS 1**'s Default keywords in PHP is empty:
> 
> ![image](https://private-user-images.githubusercontent.com/90293/357430585-ca87fadd-e852-4625-b536-e9c463e097b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjIxMzcsIm5iZiI6MTcyMzU2MTgzNywicGF0aCI6Ii85MDI5My8zNTc0MzA1ODUtY2E4N2ZhZGQtZTg1Mi00NjI1LWI1MzYtZTljNDYzZTA5N2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE1MTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZDhhZTM1NWYxNWY3MTIyMTQ1NWUyMjQ1ZjExNjU5ZWY5ZjJkNTA5NTk5MTdlNjkyYmZhYTE5ZDc1NDk4YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ADEmgFXkRVuqLJBPpzFtsjsMmq7C9nQdy1ZXV_sHqqo)
> The path of langs.xml is `%APPDATA%\notepad++\langs.xml`. Is it normal?

That's because for `substyle1`, `substyle2`, and `substyle3`, I called them `PREDEFINED` and `FUNCS AND METHODS 1` and `FUNCS AND METHODS 2`, which are shown in your screenshot.  That's why there's only five ones called `USER KEYWORDS #` in your screenshot, because `substyle4` - `substyle8` weren't pre-populated, but the first three were.

> > I think we would eventually regret treating it differently to a "normal" keyword list, when the user won't see the technical difference, and the Lexilla team treats it as the official way to get additional keyword lists....
> 
> Sorry, I don't follow you. Could you elaborate it please?

From the user perspective, there is currently no difference between the `instre1` list and the `substyle1` list, in terms of how they interact with it from the Style Configurator, or in terms of the fact that once they set the colors and the keyword list, the `substyle#` behave just like the `instre1`.  

As a result, I think it would come as a surprise to them if everything else were the same, but that they could not edit langs.xml list for the `substyle#`-based ones even though they can for the `instre#`- and `type#`-based lists.  I don't see a good reason to add more code to _take away_ that power from the user (or from a user's IT department) when it will work for them as currently implemented, and when it would then make it different in their mind from the other keyword lists.  

The responses I would expect from users, based on this confusion: "Why is this keyword list different than the other keyword list(s) for this language?  Why won't it let me add Default keywords in langs.xml?  If it's a second-class citizen, does that mean it doesn't work as well, or is dangerous to use compared to the other keyword list?  Please make it the same as the other keyword lists.  GIVE ME THE ABILITY TO ADD DEFAULT KEYWORDS IN langs.xml FOR REASON XYZ".  

To sum up my arguments:
- it's more natural to the user to treat both keyword lists identically
- it gives more power to the user right now
- the code is cleaner and less confusing
- it will be easier to give it to them now with the full power than it would be to add in the logic to disable that aspect of SubStyles and then try to remember how to add it back into the code in the future when users ask for it

2024-08-13 15:52 UTC, pryrt commented
... To clarify, my arguments about the user-confusion about the differences is only important for your question, "should people have any way to add their default keywords manually in langs.xml, in this feature".  

With respect to Alan's idea, of just hiding the Default box when there aren't any default keywords for a SubStyle, I could see why that would help reduce confusion for the user (so there isn't the extra empty box).  He's shown me where to go in the code to implement the logic to show or hide those GUI elements, so if you wanted me to hide that on SubStyles that don't have defaults, I could do that.  (If the user ever added defaults to langs.xml, then the next time they ran, the Defaults box would show up, so they can see those values.)

2024-08-13 18:30 UTC, alankilborn commented
I'm getting named-dropped a lot here (fine), but in short my argument was that I thought when user selects _USER KEYWORDS 1_ he doesn't mind seeing a box titled _User Defined Keywords_, but he's confused when he sees another box called _Default keywords_.

2024-08-13 18:34 UTC, pryrt commented
If I had called them `EXTRA KEYWORDS #` instead of `USER KEYWORDS #`, would that have alleviated your original concern?

2024-08-13 18:40 UTC, alankilborn commented
> If I had called them `EXTRA KEYWORDS #` instead of `USER KEYWORDS #`, would that have alleviated your original concern?

If that had happened, I probably wouldn't have keyed in on it.
It's fine as is if it doesn't bother anyone else participating in this discussion or reading this thread.

2024-08-13 21:59 UTC, donho commented
@pryrt 
> That's because for substyle1, substyle2, and substyle3, I called them PREDEFINED and FUNCS AND METHODS 1 and FUNCS AND METHODS 2, which are shown in your screenshot. That's why there's only five ones called USER KEYWORDS # in your screenshot, because substyle4 - substyle8 weren't pre-populated, but the first three were.

OK, I see.
In this case, I would change the substyle1, substyle2, and substyle3 to substyle6, substyle7, and substyle8 respectively, so if any user want to add their user-defined keywords, they add in substyle1 and they can see their keywords are shown in USER KEYWORDS 1's Default keywords in PHP - that'll reduce a lot of confusion.

I also suggest to add comment for the explanation of user-defined usage in langs.model.xml here:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<NotepadPlus>
   <!-- The key words of the supported languages, don't touch them! -->
   <!-- For the language C, C++... you can add your own keywords into substyle1..6 ... 
   blablabla... -->
   <Languages>
   ...
```

> On the SubStyle-based entries, hide the Default keywords entries if langs.xml doesn't define default keywords for it. (But for ones like PHP, where I used some of the substyle# entries for splitting up the 9000-keyword instre1, or if any user edits their own langs.xml, still show the Default keywords if they do populate the "default" values.)

There's nothing to hide in this case - if the default keywords could not make user know about this ability, at least it's harmless.

2024-08-13 22:01 UTC, donho requested changes
1. change the substyle1, substyle2, and substyle3 to substyle6, substyle7, and substyle8 respectively.
2. Add the comment in langs.model.xml for the explanation.

2024-08-14 18:01 UTC, donho approved these changes

2024-08-14 18:01 UTC, closed without merging