[xml] Update german.xml v8.7
notepad-plus-plus/notepad-plus-plus pull request #15623
Opened 2024-09-12 06:06 UTC by schnurlos

Fix some shortcuts

2024-09-13 08:27 UTC, MarkusBodensee commented
@schnurlos 
Since you are on it: In Line 423 and 424, item "11008" and "11009", you can remove the word "Nach" from the Item names. (The other items from this submenu don't have it either.) Because "nach" is already given in the Menu Entry one above which is in Line 92, item "window-sortby". See:
```
<Item id="11008" name="Nach Inhaltslänge aufsteigend"/>
<Item id="11009" name="Nach Inhaltslänge absteigend"/>
```

`<Item subMenuId="window-sortby" name="Sortieren nach"/>`

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7221647b7490a223a0026a0184b4fa7990f281aa/PowerEditor/installer/nativeLang/german.xml#L424

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7221647b7490a223a0026a0184b4fa7990f281aa/PowerEditor/installer/nativeLang/german.xml#L92

2024-10-19 15:15 UTC, donho commented
@schnurlos 
Could you solve the conflict?

2024-10-20 14:13 UTC, donho requested changes
Restore "Global override"

2024-10-20 14:13 UTC, donho commented on PowerEditor/installer/nativeLang/german.xml
> +					<Item id="2235" name="Was bedeutet 'Globale Überschreibung'?"/>
"Global override" should not be translated.

2024-10-20 16:34 UTC, donho approved these changes

2024-10-20 16:40 UTC, closed without merging