[xml] russian.xml hot fix RC v8.7
notepad-plus-plus/notepad-plus-plus pull request #15622
Opened 2024-09-12 00:07 UTC by GOLEM777

2024-10-19 21:22 UTC, donho commented
@GOLEM777 
Could you resolve the conflict please?

2024-10-20 13:43 UTC, donho requested changes
1. Restore "Global override"
2. Solve the conflict

2024-10-20 13:43 UTC, donho commented on PowerEditor/installer/nativeLang/russian.xml
> +					<Item id="2235" name="Что значит Глобальное Замещение?"/>
"Global override" should not be translated.

2024-10-20 16:06 UTC, GOLEM777 commented
Problem in block 
```
<<<<<<< patch-45
					<ComboBox id="6307">
						<Element name="Бездействие"/>
						<Element name="Свернуть в"/>
						<Element name="Закрыть в"/>
					</ComboBox>
					<Item id="6308" name="системный трей"/>
=======
>>>>>>> master
```

2024-10-20 16:12 UTC, GOLEM777 commented
Patch queue conflict.
Need to recreate. This has happened before.
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cd45afc0208f92c21afd286ce3f691f6f32d1989

2024-10-20 16:13 UTC, closed without merging

2024-10-23 19:15 UTC, roysten69 commented
![Designer (26)](https://github.com/user-attachments/assets/0fad5c67-96bb-4a10-8123-4b3e8a6c802a)