Add ability to open/copy selected files from Search-results, not always ALL files
notepad-plus-plus/notepad-plus-plus pull request #15763
Opened 2024-11-05 11:52 UTC by alankilborn

Fix #15741

@donho You didn't get back to replying to the issue to say if you liked the idea or not, but there was not a lot of code to this so I just went ahead with it.

Note that changes to `ScintillaEditView.*` are simply to change two `getLine` functions into `const` functions (which they should have been even without this issue).  Note that the `const` is required for the code changes of this PR to build without error.

2024-11-13 20:44 UTC, donho requested changes
Please consider the remark if you have no better suggestion.

2024-11-13 21:06 UTC, alankilborn commented on PowerEditor/installer/nativeLang/english_customizable.xml
> +			<finder-open-all value="Open Selected Pathname(s)"/>
I think it is OK either way, so I like the shorter one slightly better.

As (I think) English is a 100% language for @pryrt, maybe he has an opinion here?

2024-11-13 21:13 UTC, pryrt commented on PowerEditor/installer/nativeLang/english_customizable.xml
> +			<finder-open-all value="Open Selected Pathname(s)"/>
I have a slight preference for the shorter as well, but both communicate the action clearly to me.

2024-11-13 21:14 UTC, alankilborn commented on PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp
> +vector<wstring> Finder::getResultFilePaths(bool onlyInSelectedText) const
`getResultFilePaths()` is called 3 times, not 2.
The 3rd call (using default argument of `false`) is in code that didn't change so it doesn't show up in the diffs from this PR.

That 3rd call is when user executes this:
![image](https://github.com/user-attachments/assets/73d1f354-6985-4616-a5ac-45577bf17ea8)
For this case I chose to retain the behavior of searching all (not selected) pathnames.
But maybe this case should also be selected?

2024-11-13 21:25 UTC, donho commented on PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp
> +vector<wstring> Finder::getResultFilePaths(bool onlyInSelectedText) const
OK, please keep the name and argument.
OTOH, please remove the default value and call it always with value:
`vector<wstring> fileNames = findInFolderInfo->_pSourceFinder->getResultFilePaths(false);`

2024-11-14 13:28 UTC, alankilborn commented on PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp
> +vector<wstring> Finder::getResultFilePaths(bool onlyInSelectedText) const
OK, changed in newest commit.

2024-11-14 14:40 UTC, donho approved these changes

2024-11-14 15:01 UTC, closed without merging