[xml] Update italian.xml
notepad-plus-plus/notepad-plus-plus pull request #15774
Opened 2024-11-09 09:09 UTC by conky77

2024-11-20 17:06 UTC, donho requested changes
Need to change for aligning with the master

2024-11-20 17:06 UTC, donho commented on PowerEditor/installer/nativeLang/italian.xml
> +			<finder-copy-paths value="Copia Percorso/i selezionati"/>
Need to change

2024-11-20 17:06 UTC, donho commented on PowerEditor/installer/nativeLang/italian.xml
> +			<finder-open-all value="Apri tutti quelli selezionati"/>
Need to change

2024-11-21 22:07 UTC, closed without merging

2024-11-23 08:35 UTC, conky77 commented
Since I wasn't in time, I created a new Pull Request