[xml] Update Bulgarian localization
notepad-plus-plus/notepad-plus-plus pull request #15799
Opened 2024-11-13 19:42 UTC by rddim

* Add Pin tab feature · notepad-plus-plus/notepad-plus-plus@ce58b42

2024-11-15 21:13 UTC, NEKolev commented
Не е ли по-подходящо да се използва "минимизиране" от "намаляване"?

2024-11-20 16:25 UTC, donho requested changes
Change the labels to the correct ones

2024-11-20 16:25 UTC, donho commented on PowerEditor/installer/nativeLang/bulgarian.xml
> +			<finder-copy-paths value="Копиране на избран(ите) път(ища)"/>
Need to change

2024-11-20 16:25 UTC, donho commented on PowerEditor/installer/nativeLang/bulgarian.xml
> +			<finder-open-all value="Отваряне на избран(ите) път(ища)"/>
Need to change

2024-11-20 19:17 UTC, rddim commented
@NEKolev 
Възможно е. Опитвам се да използвам колкото се може по-малко чужди думи...

2024-11-20 19:17 UTC, rddim commented on PowerEditor/installer/nativeLang/bulgarian.xml
> +			<finder-copy-paths value="Копиране на избран(ите) път(ища)"/>
Done

2024-11-20 19:17 UTC, rddim commented on PowerEditor/installer/nativeLang/bulgarian.xml
> +			<finder-open-all value="Отваряне на избран(ите) път(ища)"/>
Done

2024-11-20 19:45 UTC, donho approved these changes

2024-11-20 19:48 UTC, closed without merging