[xml] Update Romanian translation for Notepad++ 8.7.2
notepad-plus-plus/notepad-plus-plus pull request #15814
Opened 2024-11-17 12:14 UTC by AndreiMiloiu

2024-11-20 15:26 UTC, donho commented
@AndreiMiloiu 
It's not normal to me that the localization has a lot of small ajustations during 1 year:
https://github.com/notepad-plus-plus/notepad-plus-plus/commits/master/PowerEditor/installer/nativeLang/romanian.xml

Could do your major modification in this PR, then there are only added or deleted items in the future PR?

2024-11-20 22:19 UTC, AndreiMiloiu commented
These are the final adjustments. I hope there is no mistake, typo or untranslated string left.

2024-11-21 16:04 UTC, donho requested changes
New added items for translations are not present. Please check the updated english.xml

2024-11-21 17:07 UTC, AndreiMiloiu commented
Done! I know I promised I don't have anything to change anymore. However, I found some small corrections to do and I did them. I hope everything is good now.

2024-11-21 18:23 UTC, donho requested changes
Please check the add item in english.xml on master to update your localization file!
Also make sure all the translation has been modified as you want for once: because all the unnecessary modified items won't be accepted in the future PR.

2024-11-21 18:23 UTC, donho commented on PowerEditor/installer/nativeLang/romanian.xml
>  			<finder-copy-paths value="Copiază numele căii(căilor) selectat(e)"/>
Need to change

2024-11-21 18:23 UTC, donho commented on PowerEditor/installer/nativeLang/romanian.xml
> +            <finder-open-all value="Deschide calea (căile) selectat(e)"/>
Need to change

2024-11-21 18:23 UTC, donho commented on PowerEditor/installer/nativeLang/romanian.xml
>                      <ComboBox id="6347">
Need to add one more item.

2024-11-21 22:14 UTC, donho commented
@AndreiMiloiu 
Have all the modifications been done?

2024-11-21 22:53 UTC, AndreiMiloiu commented
Yes! All of them!

2024-11-22 01:40 UTC, donho approved these changes

2024-11-22 01:43 UTC, closed without merging