[xml] Update german.xml
notepad-plus-plus/notepad-plus-plus pull request #15865
Opened 2024-11-28 06:45 UTC by schnurlos

Following https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2c1212cba5372b9777d583810c981a8c725fd18f & https://github.com/notepad-plus-plus/notepad-plus-plus/commit/287c85f8f0ba792c538f633205e10976d815da02

2024-11-29 17:15 UTC, donho requested changes
Please add a new entry also in Tabbar context menu, as latest commit in english.xml:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f18d99e24cb3609f912e7c7bf0f1d3de2b48268f

2024-12-01 09:19 UTC, schnurlos commented
@donho done

2024-12-02 12:13 UTC, CennoxX commented on PowerEditor/installer/nativeLang/german.xml
> +				<Item CMDID="44048" name="Tab Fixieren" alternativeName="Tab Lösen"/>
The verbs should be written in lower case: "Tab fixieren" and "Tab lösen"

2024-12-02 12:15 UTC, CennoxX commented on PowerEditor/installer/nativeLang/german.xml
> +					<Item id="6109" name="Farbe für Inaktive Tabs ändern"/>
"Inaktive Tabs" should be lower case: "inaktive Tabs" as it's not at the beginning of a sentence. Or a slightly different wording: "Farbe inaktiver Tabs ändern"

2024-12-04 19:20 UTC, donho approved these changes

2024-12-04 19:23 UTC, closed without merging