Find encoding for .nfo, .html, .xml files on saving and for .nfo on opening
notepad-plus-plus/notepad-plus-plus pull request #15889
Opened 2024-11-30 21:41 UTC by pawelzwronek

While fixing #15826 I found some constrains related to .nfo extension. This PR tries to remove them.

1. Detect encoding on saving `.nfo`
    Before:
    When pasting 437(OEM-US) codepage content(e.g. `░▒▓│┤╡╢╖╕╣║╗╝╜╛┐`) to untitled(UTF8) tab and then saving it as `.nfo` file, N++ shows `Are you sure you want to reload the current file and lose the changes made in Notepad++?` which might be confusing. When 'Yes' selected conversion is done and pasted text changes to `ΓûæΓûÆΓûôΓöéΓöñΓòíΓòóΓòûΓòòΓòúΓòæΓòùΓò¥Γò£Γò¢ΓöÉ`. When 'No' is selected, no conversion is done and the text doesn't change.
    User is unable to change codepage of saved/opened `.nfo` file.

    Now:
    After saving `.nfo` file codepage is set to 437 without asking.
    User can change codepage of saved/opened `.nfo' file.

3. Detect encoding on saving for `.html`/`.xml`
    Before:
    When Saving html code of untitled(UTF8) tab where encoding can be detected from it's content, encoding stays UTF8.
    
    Now:
    Encoding is detected from the content and set accordingly.

Fix #8823
Fix #9153
Fix #13905
Fix #15826

2024-12-02 17:49 UTC, donho commented
@pawelzwronek 
> Detect encoding on saving for .html/.xml
Before:
When Saving html code of untitled(UTF8) tab where encoding can be detected from it's content, encoding stays UTF8.

I can't reproduce the bug you've describe.
Could you provide more detail?

2024-12-02 17:55 UTC, pawelzwronek commented
1. Paste `<meta http-equiv="Content-Type" content="text/html; charset=windows-1251"/>` into new untitled tab
2. Save as .html
3. Encoding it still UTF8

2024-12-02 18:02 UTC, pawelzwronek commented
Btw. encoding detection regexp misses some common cases e.g. when there is no space after `;`: `content="text/html;charset=windows-1251"/>` or when charset is alone: `<meta charset="windows-1251">`. Would you like me to fix that?

2024-12-02 18:09 UTC, donho commented
> Paste <meta http-equiv="Content-Type" content="text/html; charset=windows-1251"/> into new untitled tab
Save as .html
Encoding it still UTF8

So what's the problem? I don't consider it as bug.
Users can set any encoding they want anyway.

2024-12-02 18:15 UTC, donho requested changes
nfo ext indeed imposes OEM-US - which is bad, and it should be fixed.
Please remove the part of detection on saving html/xml.

2024-12-02 19:09 UTC, pawelzwronek commented
Yep, mixing those two changes into one PR is wrong. I'll remove .html related code.

But please consider this use-case as a feature for a new PR, when saving .html file:
Paste:
```html
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
</head>
<body>
Ax 	NBSP 	¡ 	¢ 	£ 	¤ 	¥ 	¦ 	§ 	¨ 	© 	ª 	« 	¬ 	SHY 	® 	¯</br>
Bx 	° 	± 	² 	³ 	´ 	µ 	¶ 	· 	¸ 	¹ 	º 	» 	¼ 	½ 	¾ 	¿</br>
Cx 	À 	Á 	Â 	Ã 	Ä 	Å 	Æ 	Ç 	È 	É 	Ê 	Ë 	Ì 	Í 	Î 	Ï</br>
Dx 	Ð 	Ñ 	Ò 	Ó 	Ô 	Õ 	Ö 	× 	Ø 	Ù 	Ú 	Û 	Ü 	Ý 	Þ 	ß</br>
Ex 	à 	á 	â 	ã 	ä 	å 	æ 	ç 	è 	é 	ê 	ë 	ì 	í 	î 	ï</br>
Fx 	ð 	ñ 	ò 	ó 	ô 	õ 	ö 	÷ 	ø 	ù 	ú 	û 	ü 	ý 	þ 	ÿ</br>
</body>
```
into untitled tab. Save as .html. Open in web browser. You'll see:

![obraz](https://github.com/user-attachments/assets/9cf70593-590b-4bd7-97af-8dbf222d88ae)

When proposed autodetection would work, encoding of saved file would switch to ISO-8859-1 and you will see correct encoded characters in the browser.

2024-12-02 19:29 UTC, donho commented
@pawelzwronek 
You can always create the feature request, and we will see if it's needed by other users.

2024-12-03 15:58 UTC, donho commented
@pawelzwronek 
Thank you for the modification. Unfortunately, the fix of this PR is still complex with a lot of refactoring (which might bring some regression). 
Therefore PR #15902 which keeps the same logic will be used.
Thank you again for your contribution.

2024-12-03 15:58 UTC, closed without merging