Prevent search from running with unintended In-selection parameter
notepad-plus-plus/notepad-plus-plus pull request #15995
Opened 2024-12-30 13:27 UTC by alankilborn

Fix #14897 #14624 #15992

2024-12-30 13:29 UTC, alankilborn commented
@xomx @donho Comments?

2024-12-30 13:29 UTC, alankilborn commented
![image](https://github.com/user-attachments/assets/e2fa8050-b8b7-4c3a-bd66-ce0b8ec39cef)

2025-01-01 21:54 UTC, xomx commented
@alankilborn 
It will take me some time to get back to some coding for N++. So for now, I will only comment from a user's perspective.

- I tried the PR binary and it works as promised, now I am stopped when I try to directly click on some action button in the opened semi transparent Find-dlg if the "In selection" gets auto-changed somehow, good!
- maybe also add a tooltip for the Find-dlg "In selection" checkbox pointing to the Preferences setting/explanation(?)
- but I have to admit that I have here the "manual" control myself (Preferences > Searching > Minimum Size for Auto-Checking "In selection": 0) , I do not like this automation much as it has already bitten me several times

2025-01-01 22:03 UTC, alankilborn commented
@xomx Thank you for trying it and for your comments.

I suppose I was specifically looking for comments about any potential downsides to the use of PeekMessage in this application.

>I do not like this automation much as it has already bitten me several times

Maybe this PR, in its final form, will take the "bite" out of the feature.

2025-01-04 11:25 UTC, donho commented
> ![image](https://private-user-images.githubusercontent.com/77065706/399300728-e2fa8050-b8b7-4c3a-bd66-ce0b8ec39cef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NjU4MzMsIm5iZiI6MTczNTk2NTUzMywicGF0aCI6Ii83NzA2NTcwNi8zOTkzMDA3MjgtZTJmYTgwNTAtYjhiNy00YzNhLWJkNjYtY2UwYjhlYzM5Y2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDA0Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YzdlOWQxOWQ2OWE2OTM4MmQ2Nzc1OGJmNDYwODRjNWE2Y2I2MmI5YTdiMzk1MTUyNWJlOGFhNzljYmNhNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qp6-zEHpZp7OEOeaA_oLJpeCaTwXFNoe7y_sbbOSwsw)

I would use:
***The "In Selection" checkbox state has been automatically modified.***
***Please verify the search condition before performing the replace or mark action.***

2025-01-04 11:29 UTC, donho requested changes
1. Please set the message box modal.
2. Please modify the content of message.
3. Make the message localizable.

2025-01-04 11:29 UTC, donho commented on PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp
> +				::MessageBox(NULL, L"The state of 'In selection' has automatically "
The message box should be modal for blocking of Find/Replace dialog's access.

2025-01-04 11:36 UTC, alankilborn commented
@donho said:

> "Please verify the search condition before performing the replace or mark action."

The bug can happen with _Find All in Current Document_ or _Count_ actions as well, that's why the text I used was more generic and simply said "search operation".

Wouldn't user be confused if he pressed _Count_ and the msgbox said "...before performing the replace or mark action" ?

2025-01-04 12:24 UTC, alankilborn commented
How about simply saying "Please verify the search condition before continuing" ??

2025-01-05 02:15 UTC, donho commented
> Wouldn't user be confused if he pressed Count and the msgbox said "...before performing the replace or mark action" ?

I see.
Let's use ***Please verify the search condition before performing the action.***

2025-01-06 06:22 UTC, donho requested changes
Please consider the requested changes

2025-01-06 06:22 UTC, donho commented on PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp
Please add the following comment here:
/*
In the scenario where the user clicks the action button (Count, Find All in Current Document, Replace All, Mark All, or Clear All marks) without activating the Find/Replace dialog, the "In Selection" checkbox could be auto-changed after the button click. To prevent the search from running with this unintended state, the search message has been removed from the queue. Then, launch a message box to alert the user that the search didn't run and they need to verify the settings.
*/

2025-01-06 06:22 UTC, donho commented on PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp
> +				// search window while the msgbox is still open
Please remove the comment - the message auto-explains our intention.

2025-01-06 06:22 UTC, donho commented on PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp
> +					L"The \"In selection\" checkbox state has been automatically modified. Please verify the search condition before performing the action.",
Please break down the one line sentence `The "In selection" checkbox state has been automatically modified. Please verify the search condition before performing the action.` into 2 lines.

2025-01-06 06:22 UTC, donho commented on PowerEditor/installer/nativeLang/english.xml
> +			<FindAutoChangeOfInSelectionWarning title="Search warning" message="The &quot;In selection&quot; checkbox state has been automatically modified. Please verify the search condition before performin
Please break down the one line sentence `The "In selection" checkbox state has been automatically modified. Please verify the search condition before performing the action.` into 2 lines.

2025-01-07 06:31 UTC, donho requested changes
Please consider the suggestion.

2025-01-07 06:31 UTC, donho commented on PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp
> +						while (PeekMessage(&msg, ::GetDlgItem(_hSelf, id), 0, 0, PM_REMOVE))
@alankilborn 
Sorry for not pointing out the problem on the previous review:
Though there must be the message of button clicked action logically, the while loop could make a dead lock if there's no message in the queue. According the [online doc](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-peekmessagea):
`If no messages are available, the return value is zero.`

As a result, I would suggest the following code for preventing infinit loop & improving the readability:
```cpp
if (inSelChecked != origInSelChecked)
{
	const std::vector<int> inSelActionIds = { IDCCOUNTALL, IDC_FINDALL_CURRENTFILE, IDREPLACEALL, IDCMARKALL, IDC_CLEAR_ALL };
	for (const auto& id : inSelActionIds)
	{
		MSG msg;
		if (PeekMessage(&msg, ::GetDlgItem(_hSelf, id), 0, 0, PM_REMOVE))
		{
			isInSelectionAutoChange = true;
			break;
		}
	}
}
```

2025-01-08 08:03 UTC, closed without merging