Update slovak.xml
notepad-plus-plus/notepad-plus-plus pull request #8646
Opened 2020-07-31 06:08 UTC by kubalav

2020-09-08 17:09 UTC, donho commented
@kubalav 
You opened also this PR:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8636
Which one should I take?

2020-09-08 17:19 UTC, kubalav commented
This one is the latest. I closed previous PR.

2020-09-08 17:37 UTC, donho commented
So did you check the following link to make sure your PR include everything ?
http://download.notepad-plus-plus.org/repository/MISC/diff/english.diff.htm

2020-09-09 00:14 UTC, donho commented
@kubalav  Please let me know when your update is done.

2020-09-09 04:57 UTC, kubalav commented
Done.

2020-09-09 13:16 UTC, donho requested changes
Please remove `&amp;` in front of 'F'.

2020-09-09 13:16 UTC, donho commented on PowerEditor/installer/nativeLang/slovak.xml
> +                <Item id="2032" name="&amp;Formát"/>
Sorry I just fixed an issue regarding it: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/55d671719c8f00f02ed32b15575bc2e6587a5e30
`&amp;` in front of 'F' should be removed.

2020-09-09 16:46 UTC, donho approved these changes

2020-09-09 16:49 UTC, closed without merging