Fix for #9266
notepad-plus-plus/notepad-plus-plus pull request #9267
Opened 2020-12-14 20:48 UTC by chcg

- allow UTF-8 input for plugin autor and description
- update nlohmann json to v3.9.1 with performance and security improvements

2020-12-14 20:56 UTC, sasumner reviewed
Why only author and description changed to CP_UTF8?

2020-12-14 21:15 UTC, chcg commented
Just to be conservative in the change and it is unlikely that unicode is used for http links, foldernames, sha256 key and the version.

2020-12-15 12:57 UTC, sasumner commented
@chcg Just FYI because it appears you didn't know:
If you put `Fix #xxxx` as the first line of your PR comments, it will automagically link it back to issue "xxxx"

2020-12-15 13:22 UTC, chcg commented
@sasumner Thanks for the hint. Indeed I was not aware of that.

2020-12-15 15:10 UTC, donho commented
@chcg 
Why do we need to update json.hpp ?

2020-12-15 15:26 UTC, chcg commented
The update of nlohmann json to v3.9.1 is not necessary for the GUI change,

2020-12-15 17:19 UTC, donho commented
@chcg 
Then please remove the update part - I will take in charge of the update of "json.hpp".

2020-12-15 17:20 UTC, donho requested changes
Restore "json.hpp" as it was.

2020-12-15 17:41 UTC, donho commented
Thank you @chcg !

2020-12-15 17:43 UTC, chcg commented
> 
> 
> Restore "json.hpp" as it was.

Reverted to old json.hpp version.

2020-12-15 18:23 UTC, donho approved these changes

2020-12-15 18:29 UTC, closed without merging