Update taiwaneseMandarin.xml
notepad-plus-plus/notepad-plus-plus pull request #9646
Opened 2021-03-12 19:41 UTC by zica87

2021-03-20 01:37 UTC, donho requested changes
Change from:
`<Item id="6113" name="按兩下關閉文件"/>`
to:
`<Item id="6113" name="滑鼠點兩下關閉文件"/>`

2021-03-20 01:37 UTC, donho commented on PowerEditor/installer/nativeLang/taiwaneseMandarin.xml
> +                    <Item id="6113" name="按兩下關閉文件"/>
is it better "滑鼠點兩下關閉文件" ?

2021-03-20 09:25 UTC, zica87 commented on PowerEditor/installer/nativeLang/taiwaneseMandarin.xml
> +                    <Item id="6113" name="按兩下關閉文件"/>
OK.

2021-03-22 18:40 UTC, donho commented
@zica87 
Could you complete the request please?

2021-03-26 14:55 UTC, donho commented
Close due to no reply of PR author.

2021-03-26 14:55 UTC, closed without merging