Widen Default Language control in Preferences for New Document
notepad-plus-plus/notepad-plus-plus pull request #9647
Opened 2021-03-13 00:19 UTC by sasumner

Fix #9642

After:

![image](https://user-images.githubusercontent.com/30118311/111011550-c8488c80-8367-11eb-9e5c-f780ad1d4487.png)

2021-03-14 09:17 UTC, mere-human approved these changes

2021-03-18 15:14 UTC, donho commented
I would change in the following way:

![image](https://user-images.githubusercontent.com/90293/111649767-f9600b80-8804-11eb-9a44-ce35f9316154.png)

2021-03-18 15:16 UTC, donho requested changes
Not change Y position of item but enlarge the group box.

2021-03-18 20:22 UTC, sasumner commented
![image](https://user-images.githubusercontent.com/30118311/111692612-02051180-8806-11eb-9d45-3efd4c354e5b.png)

2021-03-26 00:18 UTC, donho approved these changes

2021-03-26 00:26 UTC, closed without merging