Update dutch.xml
notepad-plus-plus/notepad-plus-plus pull request #9692
Opened 2021-03-24 11:07 UTC by RockyTDR

Updated Dutch translations, according to the following commits to the source strings:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/926e6e97d82b3d63103cb2297b372af5cd469ca6

2021-03-27 20:18 UTC, MAPJe71 requested changes

2021-03-27 20:18 UTC, MAPJe71 commented on PowerEditor/installer/nativeLang/dutch.xml
> -            <find-status-search-failed value="Zoeken: zoeken mislukt"/>
Why translate this back to english?

2021-05-12 17:39 UTC, donho commented
@RockyTDR 
Could you please check the latest report of the old localization file vs new localization file to make sure if your PR updated?
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9854

Thank you!

2021-05-12 18:10 UTC, RockyTDR commented
@donho Done! Dutch translations are fully up-to-date!

2021-05-12 19:07 UTC, closed without merging