Add "Assign file type" checkbox to Save As dialog
notepad-plus-plus/notepad-plus-plus pull request #9732
Opened 2021-04-06 09:33 UTC by mere-human

Fix #9515

2021-04-06 09:35 UTC, mere-human commented
**How it works:**
_Save As_ dialog now has _Assign file type_ checkbox (default is ON).
If it's ON, the file type (in dialog drop-down) as well as file extension is set based on document language.
If checkbox is OFF, then the file type is set to `*.*` and the file extension isn't added.
The checkbox value is remembered between runs.

**Demo:**

https://user-images.githubusercontent.com/9664141/113690787-72e86c80-96d4-11eb-9031-1b7f23212306.mp4

2021-04-06 23:47 UTC, donho commented
Just a suggestion:
Using "Apply current doc. language filter" (instead of "Assign file type") may more relevant for users.

2021-04-07 08:49 UTC, mere-human commented
> Using "Apply current doc. language filter" (instead of "Assign file type") may be more relevant for users.

This seems too long as for me. At least, it could be "Apply file language filter" or something like this.

But there are more ideas. I'm not sure what is the best option yet.
Please, see the latest comment here https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9515#issuecomment-814378151 and links to community forum.

2021-04-13 07:59 UTC, mere-human commented
I should probably remove the checkbox from the preferences.

2021-04-14 22:59 UTC, donho reviewed
1. Remove getNppGUIMutable(). Use getNppGUI instead.
2. Change IDC_CHECK_AUTOUPDATE control's Y position.

2021-04-14 22:59 UTC, donho commented on PowerEditor/src/WinControls/Preference/preference.rc
>      CONTROL         "Enable Notepad++ auto-updater",IDC_CHECK_AUTOUPDATE,"Button",BS_AUTOCHECKBOX | BS_MULTILINE | WS_TABSTOP, 37, 78, 210, 10
![image](https://user-images.githubusercontent.com/90293/114788493-da13ba00-9d81-11eb-9159-205d7f25f2b0.png)

IDC_CHECK_AUTOUPDATE should be made lower too.

2021-04-15 01:46 UTC, donho requested changes
1. Remove getNppGUIMutable(). Use getNppGUI instead.
2. Change IDC_CHECK_AUTOUPDATE control's Y position.

2021-04-15 08:15 UTC, mere-human commented on PowerEditor/src/Parameters.h
> +	NppGUI& getNppGUIMutable() { return _nppGUI; }
`const_cast` is bad: https://stackoverflow.com/questions/10498292/c-why-is-const-cast-evil
What if I declare it as this?
`NppGUI& getNppGUI() { return _nppGUI; }`
Just a non-const overload. But the code wouldn't require `const_cast`.

2021-04-15 18:22 UTC, donho commented on PowerEditor/src/Parameters.h
> +	NppGUI& getNppGUIMutable() { return _nppGUI; }
@mere-human 
I see your point.
Please use `const NppGUI & getNppGUI() const;` as it is in the PR.
I will remove keyword `const` myself afterward.

2021-04-15 19:04 UTC, mere-human commented on PowerEditor/src/Parameters.h
> +	NppGUI& getNppGUIMutable() { return _nppGUI; }
As you wish.

2021-04-15 19:07 UTC, mere-human commented on PowerEditor/src/WinControls/Preference/preference.rc
> +    CONTROL         "Enable Notepad++ auto-updater",IDC_CHECK_AUTOUPDATE,"Button",BS_AUTOCHECKBOX | BS_MULTILINE | WS_TABSTOP, 37, 94, 210, 10
I moved it upper in the code so it corresponds to the comment that says "Enable Notepad++ auto-updater" should be always the 1st item".
It was me who added "Mute all sounds" in the wrong place 😬

2021-04-15 23:26 UTC, donho approved these changes

2021-04-15 23:35 UTC, closed without merging

2021-04-16 11:57 UTC, sasumner commented
@mere-human Hooray!  I like it.
I should cautiously add: "We'll see how it goes with users".

2021-04-16 11:59 UTC, mere-human commented
> I should cautiously add: "We'll see how it goes with users".

Users don't stop to surprise me with what they request and how they're able break our features 😄

2021-04-16 12:06 UTC, sasumner commented
>Users don't stop to surprise me with what they request and how they're able break our features

Yes, but this one is a very special case.  It seems to be one where we can't predict what will arise.
Hopefully we (you!) are "honing in" on the final solution (the one that generates no more complaints).
It has been a long saga (6+ years) starting with old/new style user questions/problems...and probably hundreds of related Community postings...sigh...

2021-04-17 10:56 UTC, sasumner commented
@mere-human 

Can you update the user manual for this feature?
Having said that, I'm not sure the best area it belongs in.
On the upside, I think I was remiss and never added the setting you just removed from the _Preferences_, so nothing will need to be removed there.

2021-04-17 11:00 UTC, mere-human commented
> @mere-human
> 
> Can you update the user manual for this feature?

Sure, I will check it. Should I write something like in my 2nd comment in this PR?

2021-04-17 11:04 UTC, sasumner commented
>like in my 2nd comment in this PR?

Very reasonable.
I'll let you create your own issue in the user manual issue tracker.
Thanks!

2021-04-17 13:36 UTC, mere-human commented
@pryrt Do you have an idea whether this should be documented and what section it belongs to?

2021-04-18 11:05 UTC, sasumner commented
>whether this should be documented

I thought we established this.
A strong YES.  :-)

>what section it belongs to?

It may need a new section.
And yes @pryrt 's thoughts on that would be super to have.
Normally there is no need to discuss open/save dialogs as everyone that uses Windows knows how they work.  !!

2021-06-01 13:28 UTC, pryrt commented
@mere-human / @sasumner ,

Have Alan Kilborn and I misunderstood the intention of the "Append extension" checkbox, as Alan describes [in the Forum here](https://community.notepad-plus-plus.org/post/66533)?  Because as I understood its intention, if you type a filename with no extension when the "Append extension" is checked, Alan and I expect it to automatically add the first extension from the current Save As type.  But in Alan's experiment on 8.0-RC2, it does _not_ append the extension if there is no extension in the file-name box.

2021-06-01 20:51 UTC, mere-human commented
> But in Alan's experiment on 8.0-RC2, it does _not_ append the extension if there is no extension in the file-name box.

Indeed, it should work as described. But it shouldn't because there is a bug.
It seems like the checkbox works as intended only when the save dialog is shown for the first time since app launch.
All subsequent calls don't work.
I'm going to fix that.

2021-06-01 20:58 UTC, mere-human commented
@pryrt  Does it work if you press Enter key or Alt+S?

2021-06-01 21:01 UTC, sasumner commented
@mere-human 

I tried it:

Enter key:  works!  (.txt extension added automagically)
Alt+s:  doesn't work (no extension added)

2021-06-03 01:17 UTC, donho commented
@mere-human So is it a regression due to this PR?
Any opened issue about it?

2021-06-03 08:26 UTC, mere-human commented
> @mere-human So is it a regression due to this PR?
> Any opened issue about it?

Yes, it is a regression.
I haven't seen any issue about it. I'll create one to document everything related.

2021-06-03 11:06 UTC, sasumner commented
>regression

Nitpick: I would call it a bug because this checkbox is new functionality -- nothing to "regress".